import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat.";

/** Potluck course — P1 community-demand batch. */
export default [
  lineFromMoves(1, "accel-dragon", "Accelerated Dragon — Line 1", ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","g6","Nc3","Bg7","Be3","Nf6","Bc4","O-O","Bb3","d6"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 1.", ["Accelerated Dragon"]),
  lineFromMoves(2, "accel-dragon", "Accelerated Dragon — Line 2", ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","g6","Nc3","Bg7","Be3","Nf6","f3","O-O","Qd2","d6"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 2.", ["Accelerated Dragon"]),
  lineFromMoves(3, "accel-dragon", "Accelerated Dragon — Line 3", ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","g6","Nc3","Bg7","Be2","Nf6","Be3","O-O","O-O","d6"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 3.", ["Accelerated Dragon"]),
  lineFromMoves(4, "accel-dragon", "Accelerated Dragon — Line 4", ["e4","c5","Nf3","g6","d4","cxd4","Nxd4","Bg7","Nc3","Nc6","Be3","Nf6","Bc4","O-O","Bb3","d6"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 4.", ["Accelerated Dragon"]),
  lineFromMoves(5, "accel-dragon", "Accelerated Dragon — Line 5", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","Nc6","Be3","e6","Qd2","a6","O-O-O","Bd7","f4","b5"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 5.", ["Accelerated Dragon"]),
  lineFromMoves(6, "accel-dragon", "Accelerated Dragon — Line 6", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","g6","Be3","Bg7","f3","O-O","Qd2","Nc6","O-O-O","Bd7","g4","Rc8"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 6.", ["Accelerated Dragon"]),
  lineFromMoves(7, "accel-dragon", "Accelerated Dragon — Line 7", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Be3","e5","Nb3","Be6","f3","Be7","Qd2","O-O","O-O-O","b5"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 7.", ["Accelerated Dragon"]),
  lineFromMoves(8, "accel-dragon", "Accelerated Dragon — Line 8", ["e4","c5","c3","d5","exd5","Qxd5","d4","Nf6","Nf3","e6","Be2","Nc6","O-O","Be7","Re1","O-O"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 8.", ["Accelerated Dragon"]),
  lineFromMoves(9, "accel-dragon", "Accelerated Dragon — Line 9", ["e4","c5","c3","Nf6","e5","Nd5","d4","cxd4","cxd4","e6","Nf3","d6","Bc4","Nb6","Bb3","N8d7"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 9.", ["Accelerated Dragon"]),
  lineFromMoves(10, "accel-dragon", "Accelerated Dragon — Line 10", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","e6","Be3","a6","f3","b5","Qd2","Bb7","O-O-O","Nbd7","g4","b4"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 10.", ["Accelerated Dragon"]),
  lineFromMoves(11, "accel-dragon", "Accelerated Dragon — Line 11", ["e4","c5","Nc3","Nc6","f4","g6","Nf3","Bg7","Bb5","Nd4","Bxd7+","Qxd7","O-O","e6","d3","Nge7"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 11.", ["Accelerated Dragon"]),
  lineFromMoves(12, "accel-dragon", "Accelerated Dragon — Line 12", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","Nc6","Ndb5","Bd7","Nxd6+","exd6","Nd5","Be7"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 12.", ["Accelerated Dragon"]),
  lineFromMoves(13, "accel-dragon", "Accelerated Dragon — Line 13", ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","g6","Nc3","Bg7","Be3","Nf6","f3","O-O","Qd2","d6","O-O-O","Bd7","g4","Rc8"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 13.", ["Accelerated Dragon"]),
  lineFromMoves(14, "accel-dragon", "Accelerated Dragon — Line 14", ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","e6","Nc3","Qc7","Be2","a6","O-O","Nf6","Be3","Bb4"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 14.", ["Accelerated Dragon"]),
  lineFromMoves(15, "accel-dragon", "Accelerated Dragon — Line 15", ["e4","c5","Nf3","e6","d4","cxd4","Nxd4","a6","Nc3","Qc7","Be2","Nf6","O-O","Bb4","Qd3","O-O"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 15.", ["Accelerated Dragon"]),
  lineFromMoves(16, "accel-dragon", "Accelerated Dragon — Line 16", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Bb5+","Bd7","Bxd7+","Qxd7","Nc3","g6","O-O","Nc6","Ndb5","O-O-O"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 16.", ["Accelerated Dragon"]),
  lineFromMoves(17, "accel-dragon", "Accelerated Dragon — Line 17", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","g6","Ndb5","Nbd7","Nxd6+","exd6","Nd5","Bg7","Ne7","Nf8","Nxc8","Ne6"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 17.", ["Accelerated Dragon"]),
  lineFromMoves(18, "accel-dragon", "Accelerated Dragon — Line 18", ["e4","c5","f4","d6","Nf3","Nf6","Nc3","g6","Bb5+","Bd7","Bxd7+","Qxd7","O-O","Bg7","d3","O-O"], "Sicilian ...g6 ...Bg7 before ...d6 — 15–18 main lines without meme-depth bloat. Line 18.", ["Accelerated Dragon"]),
];
