import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "Aggressive Queen's Gambit Declined — fight for the initiative as White.";

/** Potluck course — generated from validated templates. */
export default [
  lineFromMoves(1, "agg-qgd", "Aggressive QGD — Line 1", ["d4","d5","c4","e6","c5","a6","g4","Nd7","Bg5","a5","b3","Be7","Bc1","Ngf6","Bg2","Nxg4","Bf1","Rb8"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 1.", ["Aggressive QGD"]),
  lineFromMoves(2, "agg-qgd", "Aggressive QGD — Line 2", ["d4","d5","c4","e6","cxd5","Bd6","h3","Nf6","Kd2","a5","Rh2","Ke7","f4","b5","e4","Qf8","a4","Ng8"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 2.", ["Aggressive QGD"]),
  lineFromMoves(3, "agg-qgd", "Aggressive QGD — Line 3", ["d4","d5","c4","e6","a3","Bxa3","f4","b6","Nf3","a5","Bd2","Nf6","Ng5","Nh5","Rg1","g6","c5","c6"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 3.", ["Aggressive QGD"]),
  lineFromMoves(4, "agg-qgd", "Aggressive QGD — Line 4", ["d4","d5","c4","e6","a4","Nh6","h3","f5","Qd2","f4","Na3","Nc6","cxd5","Ne5","Rh2","Kd7","b4","a6"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 4.", ["Aggressive QGD"]),
  lineFromMoves(5, "agg-qgd", "Aggressive QGD — Line 5", ["d4","d5","c4","e6","b3","Nf6","Nc3","Nh5","h3","dxc4","Kd2","g6","Na4","Bd6","Nf3","Qg5+","Ke1","Bf4"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 5.", ["Aggressive QGD"]),
  lineFromMoves(6, "agg-qgd", "Aggressive QGD — Line 6", ["d4","d5","c4","e6","b4","a5","f4","c6","Kf2","h6","Qb3","Na6","Qe3","a4","Kf3","Ra7","Na3","b5"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 6.", ["Aggressive QGD"]),
  lineFromMoves(7, "agg-qgd", "Aggressive QGD — Line 7", ["d4","d5","c4","e6","e3","a6","f4","h6","Bd2","Qg5","Nc3","a5","Na4","c6","h4","Qg3+","Ke2","Rh7"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 7.", ["Aggressive QGD"]),
  lineFromMoves(8, "agg-qgd", "Aggressive QGD — Line 8", ["d4","d5","c4","e6","e4","a6","Nh3","g5","a3","Bd7","Nc3","Bc5","Kd2","b5","cxd5","h6","dxc5","Nc6"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 8.", ["Aggressive QGD"]),
  lineFromMoves(9, "agg-qgd", "Aggressive QGD — Line 9", ["d4","d5","c4","e6","f3","b6","Bf4","f6","g3","Be7","Qa4+","Nd7","Qb4","c6","Qxb6","h5","h3","e5"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 9.", ["Aggressive QGD"]),
  lineFromMoves(10, "agg-qgd", "Aggressive QGD — Line 10", ["d4","d5","c4","e6","f4","b5","Qa4","f5","Bd2","Nc6","Kd1","h6","Nh3","h5","Qc2","Ne5","Ng5","Nf7"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 10.", ["Aggressive QGD"]),
  lineFromMoves(11, "agg-qgd", "Aggressive QGD — Line 11", ["d4","d5","c4","e6","g3","c6","Bd2","g6","Qa4","g5","b3","Bh6","Qa3","f5","c5","Qb6","e3","f4"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 11.", ["Aggressive QGD"]),
  lineFromMoves(12, "agg-qgd", "Aggressive QGD — Line 12", ["d4","d5","c4","e6","g4","c5","Be3","Nd7","Nh3","a5","b4","Ne7","Nc3","a4","Ne4","f5","Qb3","Nb8"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 12.", ["Aggressive QGD"]),
  lineFromMoves(13, "agg-qgd", "Aggressive QGD — Line 13", ["d4","d5","c4","e6","h3","f6","Qb3","Be7","Qc2","Nd7","f4","Bb4+","Bd2","e5","g3","dxc4","dxe5","Kf7"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 13.", ["Aggressive QGD"]),
  lineFromMoves(14, "agg-qgd", "Aggressive QGD — Line 14", ["d4","d5","c4","e6","h4","f5","Bg5","Qd6","e4","Qb6","Qd3","Nc6","Qc2","fxe4","Ne2","h5","c5","Nb8"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 14.", ["Aggressive QGD"]),
  lineFromMoves(15, "agg-qgd", "Aggressive QGD — Line 15", ["d4","d5","c4","e6","Na3","g6","Qd2","e5","dxe5","Ne7","cxd5","Na6","Qh6","Qd7","h4","Kd8","Qxh7","Bg7"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 15.", ["Aggressive QGD"]),
  lineFromMoves(16, "agg-qgd", "Aggressive QGD — Line 16", ["d4","d5","c4","e6","Nc3","g5","Rb1","Qe7","Nh3","f6","Ng1","Bd7","h4","Nh6","e3","a5","g4","Ba4"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 16.", ["Aggressive QGD"]),
  lineFromMoves(17, "agg-qgd", "Aggressive QGD — Line 17", ["d4","d5","c4","e6","Nd2","h6","f3","Qf6","h3","Ke7","Qb3","g5","a3","b6","Qc2","Kd8","g4","Ke7"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 17.", ["Aggressive QGD"]),
  lineFromMoves(18, "agg-qgd", "Aggressive QGD — Line 18", ["d4","d5","c4","e6","Bd2","h5","Qb3","Nd7","Qd3","Bb4","Qh7","Be7","Bf4","Kf8","cxd5","Bf6","Be5","g5"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 18.", ["Aggressive QGD"]),
  lineFromMoves(19, "agg-qgd", "Aggressive QGD — Line 19", ["d4","d5","c4","e6","Be3","e5","Qc1","c6","g4","f6","Qd2","Qa5","Bh6","Qb6","Bg5","Nd7","Qa5","Nh6"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 19.", ["Aggressive QGD"]),
  lineFromMoves(20, "agg-qgd", "Aggressive QGD — Line 20", ["d4","d5","c4","e6","Bf4","dxc4","Na3","c3","h3","cxb2","Bd6","bxa1=B","e3","e5","dxe5","Qe7","g4","Qf6"], "Aggressive Queen's Gambit Declined — fight for the initiative as White. Line 20.", ["Aggressive QGD"]),
];
