import { mkLine, lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION =
  "The Albin Countergambit: 1.d4 d5 2.c4 e5 — seventeen lines where Black sacrifices a pawn for rapid development and the deadly d4-d3 advance.";

export default [
  mkLine(
    1,
    "albin_main_lasker",
    "Main Line — Lasker Trap",
    "Line #1 · ...Be6 and ...d3",
    "The Albin is all about that sneaky d3 pawn. Learn the main tricks here.",
    ["d4","d5","c4","e5","dxe5","d4","Nf3","Nc6","g3","Bf5","Bg2","Qd7","O-O","O-O-O","b4","Bxb4","Nbd2","f6"],
    [
      "d4.",
      "...d5 — solid queen pawn.",
      "c4.",
      "...e5! — Albin time!",
      "dxe5.",
      "...d4 — the passed pawn is your pride.",
      "Nf3.",
      "...Nc6 develops.",
      "g3.",
      "...Bf5 — bishop stays outside the pawn chain.",
      "Bg2.",
      "...Qd7 — connect and eye h3.",
      "O-O.",
      "...O-O-O — long castling for attack!",
      "b4.",
      "...Bxb4 — take the pawn.",
      "Nbd2.",
      "...f6 — undermine e5.",
    ],
    ["Albin Countergambit","Main Line"]
  ),
  mkLine(
    2,
    "albin_d3_trap",
    "d3 Pawn — Lasker Trap",
    "Line #2 · ...d3 wins material",
    "When White grabs too much, ...d3 and ...Bc5 can win a piece.",
    ["d4","d5","c4","e5","dxe5","d4","e3","Bb4+","Bd2","dxe3","fxe3","Qh4+","g3","Qe4","Kf2","Nc6"],
    [
      "d4.",
      "...d5.",
      "c4.",
      "...e5!",
      "dxe5.",
      "...d4!",
      "e3.",
      "...Bb4+ — check!",
      "Bd2.",
      "...dxe3!",
      "fxe3.",
      "...Qh4+ — fork city.",
      "g3.",
      "...Qe4 — hit e3 and h1.",
      "Kf2.",
      "...Nc6 — development wins.",
    ],
    ["Albin Countergambit","Lasker Trap"]
  ),
  lineFromMoves(3, "albin", "3.cxd5 Qxd5", ["d4","d5","c4","e5","cxd5","Qxd5","Nc3","Bb4","Bd2","Bxc3","Bxc3","Qe4+"], "If White takes d5, ...Qxd5 and ...Bb4 pin.", ["Albin Countergambit"]),
  lineFromMoves(4, "albin", "4.e4 Central", ["d4","d5","c4","e5","dxe5","d4","e4","Nc6","f4","f6","exf6","Nxf6","Nf3","Bc5"], "White pushes e4 — meet with ...Nc6 and ...f6.", ["Albin Countergambit"]),
  mkLine(
    5,
    "albin_bxc3",
    "Exchange Variation",
    "Line #5 · ...Bxc3 bxc3",
    "Trade on c3 and use the weak c3 pawn against White.",
    ["d4","d5","c4","e5","dxe5","d4","Nf3","Nc6","a3","Bg4","Nbd2","Qe7","e3","O-O-O","exd4","Nxd4"],
    [
      "d4.",
      "...d5.",
      "c4.",
      "...e5!",
      "dxe5.",
      "...d4.",
      "Nf3.",
      "...Nc6.",
      "a3.",
      "...Bg4 pins!",
      "Nbd2.",
      "...Qe7.",
      "e3.",
      "...O-O-O.",
      "exd4.",
      "...Nxd4 — central domination.",
    ],
    ["Albin Countergambit"]
  ),
  lineFromMoves(6, "albin", "5.Nbd2 Setup", ["d4","d5","c4","e5","dxe5","d4","Nf3","Nc6","Nbd2","Bg4","h3","Bxf3","Nxf3","Qe7"], "Standard ...Bg4 and ...Qe7 development.", ["Albin Countergambit"]),
  lineFromMoves(7, "albin", "Decline 3.Nf3", ["d4","d5","c4","e5","dxe5","d4","Nf3","Nc6","g3","Bf5","Bg2","Be7"], "When White declines with Nf3, grab space with ...e4.", ["Albin Countergambit"]),
  lineFromMoves(8, "albin", "Queen to a5 — Pressure", ["d4","d5","c4","e5","dxe5","d4","e3","Bb4+","Bd2","dxe3","fxe3","Qh4+","g3","Nd7","Bc3","Nh6"], "Use the queen on a5 to pressure e5 and c3.", ["Albin Countergambit"]),
  lineFromMoves(9, "albin", "6.b4 Bxb4", ["d4","d5","c4","e5","dxe5","d4","Nf3","Nc6","g3","Bf5","Bg2","Qd7","O-O","O-O-O","b4","Bxb4"], "The ...Bxb4 grab when White pushes b4.", ["Albin Countergambit"]),
  lineFromMoves(10, "albin", "4.a3 Bg4", ["d4","d5","c4","e5","e3","exd4","exd4","Nf6","Nd2","Nbd7","Ne4","Be7","Nd6+","Bxd6"], "a3 from White — develop with ...Nc6 and ...Bg4.", ["Albin Countergambit"]),
  lineFromMoves(11, "albin", "Spassky 5.g3", ["d4","d5","c4","e5","dxe5","d4","Nf3","Nc6","g3","Bf5","Bg2","Qd7","O-O","O-O-O","Nc3","Nge7"], "The g3 fianchetto line — castle long and prepare ...f6.", ["Albin Countergambit"]),
  lineFromMoves(12, "albin", "3.e3 Decline", ["d4","d5","c4","e5","e3","exd4","exd4","Nf6","Nc3","Be7","Nf3","O-O"], "White declines — take on d4 and develop normally.", ["Albin Countergambit"]),
  mkLine(
    13,
    "albin_ne5",
    "Knight e5 — Central Outpost",
    "Line #13 · ...Nge7-Ne5",
    "Get a knight on e5 and make White regret the gambit.",
    ["d4","d5","c4","e5","dxe5","d4","Nf3","Nc6","g3","Bg4","Bg2","Qd7","O-O","O-O-O","Nbd2","Nge7","a3","Ng6"],
    [
      "d4.",
      "...d5.",
      "c4.",
      "...e5!",
      "dxe5.",
      "...d4.",
      "Nf3.",
      "...Nc6.",
      "g3.",
      "...Bg4.",
      "Bg2.",
      "...Qd7.",
      "O-O.",
      "...O-O-O.",
      "Nbd2.",
      "...Nge7 — heading to e5 or g6.",
      "a3.",
      "...Ng6 — knight reroutes with purpose.",
    ],
    ["Albin Countergambit"]
  ),
  lineFromMoves(14, "albin", "4.Bf4 Bg4", ["d4","d5","c4","e5","dxe5","d4","Bf4","Nc6","Nf3","Bg4","e3","Qe7","Be2","O-O-O"], "Meet Bf4 with ...Nc6 and active piece play.", ["Albin Countergambit"]),
  lineFromMoves(15, "albin", "5.h3 Bxf3", ["d4","d5","c4","e5","dxe5","d4","Nf3","Nc6","g3","Bf5","Bg2","Qd7","O-O","O-O-O","h3","h5"], "When White plays h3, keep the initiative with ...h5.", ["Albin Countergambit"]),
  lineFromMoves(16, "albin", "Two Knights 3.Nc3", ["d4","d5","c4","e5","dxe5","d4","Nf3","Nc6","g3","Bf5","Bg2","Be7","O-O","Nh6"], "Nc3 decline — develop with ...Nc6 and ...Nf6.", ["Albin Countergambit"]),
  lineFromMoves(17, "albin", "Modern 4...a6", ["d4","d5","c4","e5","dxe5","d4","Nf3","Nc6","g3","Bf5","Bg2","a6","O-O","Qd7","b4","O-O-O"], "Prophylactic ...a6 before White's b4 push.", ["Albin Countergambit"]),
];
