import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening.";

/** Potluck course — generated from validated templates. */
export default [
  lineFromMoves(1, "anglaise", "Anglaise (English Attack) — Line 1", ["c4","Nc6","d3","a6","f4","Nb8","a3","f5","b3","b6","Nc3","d5","b4","Qd6","Kf2","g6","d4","Kd7"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 1.", ["Anglaise (English Attack)"]),
  lineFromMoves(2, "anglaise", "Anglaise (English Attack) — Line 2", ["c4","Na6","d4","d5","f3","Qd6","Qc2","Bh3","Qf5","f6","Na3","Bxf5","h3","Qb4+","Kf2","Bg4","c5","b5"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 2.", ["Anglaise (English Attack)"]),
  lineFromMoves(3, "anglaise", "Anglaise (English Attack) — Line 3", ["c4","Nh6","e3","d6","g4","a5","Ne2","g5","Rg1","b6","d4","f5","Qc2","c5","Rg2","Nc6","f4","Kd7"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 3.", ["Anglaise (English Attack)"]),
  lineFromMoves(4, "anglaise", "Anglaise (English Attack) — Line 4", ["c4","Nf6","e4","b5","f4","Nh5","Qf3","g6","Qd1","bxc4","Qa4","e5","Kf2","Bb7","h3","Be7","Qc6","f6"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 4.", ["Anglaise (English Attack)"]),
  lineFromMoves(5, "anglaise", "Anglaise (English Attack) — Line 5", ["c4","a6","f3","f5","e3","h6","h3","b6","b4","d5","d4","Be6","Rh2","Rh7","Rh1","Qc8","Qe2","Nd7"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 5.", ["Anglaise (English Attack)"]),
  lineFromMoves(6, "anglaise", "Anglaise (English Attack) — Line 6", ["c4","a5","f4","d6","d3","Bg4","Na3","Na6","e3","Bf3","Be2","e5","b3","Be7","g4","Nb4","Rb1","Bxg4"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 6.", ["Anglaise (English Attack)"]),
  lineFromMoves(7, "anglaise", "Anglaise (English Attack) — Line 7", ["c4","b6","g3","d5","cxd5","Bg4","b3","Nf6","e3","Qd7","Be2","Qd8","Nh3","Nh5","Bb2","e5","Bd3","Qg5"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 7.", ["Anglaise (English Attack)"]),
  lineFromMoves(8, "anglaise", "Anglaise (English Attack) — Line 8", ["c4","b5","f4","d6","b3","Bh3","e4","h6","Bb2","Nf6","Bd3","d5","Qe2","a6","Ba3","h5","Qe3","Bg4"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 8.", ["Anglaise (English Attack)"]),
  lineFromMoves(9, "anglaise", "Anglaise (English Attack) — Line 9", ["c4","c6","h3","e5","g3","Qf6","e4","Be7","Ke2","c5","Bg2","Qb6","h4","Kd8","f4","f6","Ke1","g6"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 9.", ["Anglaise (English Attack)"]),
  lineFromMoves(10, "anglaise", "Anglaise (English Attack) — Line 10", ["c4","c5","Nc3","e5","Nb5","a6","e3","Nc6","Qf3","Bd6","Qf5","h6","Qf4","g5","e4","Na7","Nc7+","Qxc7"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 10.", ["Anglaise (English Attack)"]),
  lineFromMoves(11, "anglaise", "Anglaise (English Attack) — Line 11", ["c4","d6","Na3","Bd7","f4","Bf5","h3","a5","Kf2","c6","b3","h5","Bb2","Rh6","Bd4","Ra6","Qb1","Qc8"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 11.", ["Anglaise (English Attack)"]),
  lineFromMoves(12, "anglaise", "Anglaise (English Attack) — Line 12", ["c4","d5","h4","Nd7","b4","Ngf6","Qc2","Ng8","Bb2","Ndf6","Qa4+","c6","Na3","Ne4","Bxg7","b5","Qd1","Bh3"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 12.", ["Anglaise (English Attack)"]),
  lineFromMoves(13, "anglaise", "Anglaise (English Attack) — Line 13", ["c4","e6","Qc2","e5","g4","Bc5","b3","Qf6","e3","c6","Qe4","Kd8","Bd3","h6","Qd5","Be7","Nh3","Qh4"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 13.", ["Anglaise (English Attack)"]),
  lineFromMoves(14, "anglaise", "Anglaise (English Attack) — Line 14", ["c4","e5","Qb3","Nc6","a4","Qh4","a5","Nh6","a6","d6","Qa4","Qd4","Qa3","Kd8","c5","Qa4","b3","b5"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 14.", ["Anglaise (English Attack)"]),
  lineFromMoves(15, "anglaise", "Anglaise (English Attack) — Line 15", ["c4","f6","Qa4","e6","g3","Be7","Bh3","c6","Qb3","Nh6","Qf3","Ba3","Bf5","Kf8","h3","Nf7","Qe3","g5"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 15.", ["Anglaise (English Attack)"]),
  lineFromMoves(16, "anglaise", "Anglaise (English Attack) — Line 16", ["c4","f5","Nf3","Kf7","d3","a5","Qc2","Kf6","Bd2","a4","Ng5","Ra5","Nf3","e6","Be3","Rd5","Qc1","b5"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 16.", ["Anglaise (English Attack)"]),
  lineFromMoves(17, "anglaise", "Anglaise (English Attack) — Line 17", ["c4","g6","Nh3","Nc6","Nc3","e6","g3","Bh6","Nf4","a6","Ne4","d5","d3","a5","Nd6+","Kd7","Bd2","cxd6"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 17.", ["Anglaise (English Attack)"]),
  lineFromMoves(18, "anglaise", "Anglaise (English Attack) — Line 18", ["d4","d5","Bf4","e6","e3","Bd6","Qg4","Bxf4","Qxg7","Qf6","Qxf6","Nxf6","exf4"], "Play 1.c4 instead of e4/d4 — traps galore and a white edge out of the opening. Line 18.", ["Anglaise (English Attack)"]),
];
