import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort.";

/** Potluck course — newest Line Kitchen additions. */
export default [
  lineFromMoves(1, "anti-london", "Anti-London System — Line 1", ["d4","d5","Nf3","Nf6","e3","e6","Bd3","Bd6","c3","O-O","O-O","c5"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 1.", ["Anti-London System"]),
  lineFromMoves(2, "anti-london", "Anti-London System — Line 2", ["d4","d5","Bf4","c5","e3","Nc6","c3","Nf6","Nd2","Qb6","Nb3","a5"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 2.", ["Anti-London System"]),
  lineFromMoves(3, "anti-london", "Anti-London System — Line 3", ["d4","d5","Bf4","Nf6","e3","e6","Nf3","Bd6","c3","O-O","Bd3","Re8"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 3.", ["Anti-London System"]),
  lineFromMoves(4, "anti-london", "Anti-London System — Line 4", ["d4","d5","Bf4","c6","e3","Nf6","Nf3","Qb6","Qd2","Nbd7","c3","e6"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 4.", ["Anti-London System"]),
  lineFromMoves(5, "anti-london", "Anti-London System — Line 5", ["d4","d5","Bf4","Nf6","e3","g6","Nf3","Bf5","c3","e6","Bd3","Bxd3","Qxd3","c5"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 5.", ["Anti-London System"]),
  lineFromMoves(6, "anti-london", "Anti-London System — Line 6", ["d4","d5","Nc3","Nf6","Bf4","c5","e3","Nc6","Nf3","Qb6","a3","e6"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 6.", ["Anti-London System"]),
  lineFromMoves(7, "anti-london", "Anti-London System — Line 7", ["d4","d5","c4","e6","c5","a6","g4","Nd7","Bg5","a5","b3","Be7","Bc1","Ngf6","Bg2","Nxg4","Bf1","Rb8"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 7.", ["Anti-London System"]),
  lineFromMoves(8, "anti-london", "Anti-London System — Line 8", ["d4","d5","c4","e6","cxd5","Bd6","h3","Nf6","Kd2","a5","Rh2","Ke7","f4","b5","e4","Qf8","a4","Ng8"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 8.", ["Anti-London System"]),
  lineFromMoves(9, "anti-london", "Anti-London System — Line 9", ["d4","d5","c4","e6","a3","Bxa3","f4","b6","Nf3","a5","Bd2","Nf6","Ng5","Nh5","Rg1","g6","c5","c6"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 9.", ["Anti-London System"]),
  lineFromMoves(10, "anti-london", "Anti-London System — Line 10", ["d4","d5","c4","e6","a4","Nh6","h3","f5","Qd2","f4","Na3","Nc6","cxd5","Ne5","Rh2","Kd7","b4","a6"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 10.", ["Anti-London System"]),
  lineFromMoves(11, "anti-london", "Anti-London System — Line 11", ["d4","d5","c4","e6","b3","Nf6","Nc3","Nh5","h3","dxc4","Kd2","g6","Na4","Bd6","Nf3","Qg5+","Ke1","Bf4"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 11.", ["Anti-London System"]),
  lineFromMoves(12, "anti-london", "Anti-London System — Line 12", ["d4","d5","c4","e6","b4","a5","f4","c6","Kf2","h6","Qb3","Na6","Qe3","a4","Kf3","Ra7","Na3","b5"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 12.", ["Anti-London System"]),
  lineFromMoves(13, "anti-london", "Anti-London System — Line 13", ["d4","d5","c4","e6","e3","a6","f4","h6","Bd2","Qg5","Nc3","a5","Na4","c6","h4","Qg3+","Ke2","Rh7"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 13.", ["Anti-London System"]),
  lineFromMoves(14, "anti-london", "Anti-London System — Line 14", ["d4","d5","c4","e6","e4","a6","Nh3","g5","a3","Bd7","Nc3","Bc5","Kd2","b5","cxd5","h6","dxc5","Nc6"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 14.", ["Anti-London System"]),
  lineFromMoves(15, "anti-london", "Anti-London System — Line 15", ["d4","d5","c4","e6","f3","b6","Bf4","f6","g3","Be7","Qa4+","Nd7","Qb4","c6","Qxb6","h5","h3","e5"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 15.", ["Anti-London System"]),
  lineFromMoves(16, "anti-london", "Anti-London System — Line 16", ["d4","d5","c4","e6","f4","b5","Qa4","f5","Bd2","Nc6","Kd1","h6","Nh3","h5","Qc2","Ne5","Ng5","Nf7"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 16.", ["Anti-London System"]),
  lineFromMoves(17, "anti-london", "Anti-London System — Line 17", ["d4","d5","c4","e6","g3","c6","Bd2","g6","Qa4","g5","b3","Bh6","Qa3","f5","c5","Qb6","e3","f4"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 17.", ["Anti-London System"]),
  lineFromMoves(18, "anti-london", "Anti-London System — Line 18", ["d4","d5","c4","e6","g4","c5","Be3","Nd7","Nh3","a5","b4","Ne7","Nc3","a4","Ne4","f5","Qb3","Nb8"], "Fight the London and Jobava — ...c5, ...Bd6, and ...Qb6 setups that take White out of comfort. Line 18.", ["Anti-London System"]),
];
