import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans.";

/** Potluck course — P1 community-demand batch. */
export default [
  lineFromMoves(1, "benoni-benko", "Benoni & Benko — Line 1", ["d4","Nf6","c4","c5","d5","e6","Nc3","exd5","cxd5","d6","e4","g6","Nf3","Bg7","Be2","O-O"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 1.", ["Benoni & Benko"]),
  lineFromMoves(2, "benoni-benko", "Benoni & Benko — Line 2", ["d4","Nf6","c4","c5","d5","b5","cxb5","a6","bxa6","Bxa6","Nc3","d6","e4","Bxf1","Kxf1","g6"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 2.", ["Benoni & Benko"]),
  lineFromMoves(3, "benoni-benko", "Benoni & Benko — Line 3", ["d4","Nf6","c4","c5","d5","b5","Qc2","bxc4","e4","d6","Bxc4","g6","Ne2","Bg7","O-O","O-O"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 3.", ["Benoni & Benko"]),
  lineFromMoves(4, "benoni-benko", "Benoni & Benko — Line 4", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 4.", ["Benoni & Benko"]),
  lineFromMoves(5, "benoni-benko", "Benoni & Benko — Line 5", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f3","O-O","Be3","c5","d5","e6","Qd2","exd5","cxd5","a6"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 5.", ["Benoni & Benko"]),
  lineFromMoves(6, "benoni-benko", "Benoni & Benko — Line 6", ["d4","Nf6","c4","g6","Nf3","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 6.", ["Benoni & Benko"]),
  lineFromMoves(7, "benoni-benko", "Benoni & Benko — Line 7", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f4","O-O","Nf3","c5","d5","e6","Be2","exd5"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 7.", ["Benoni & Benko"]),
  lineFromMoves(8, "benoni-benko", "Benoni & Benko — Line 8", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","g4","Nf6"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 8.", ["Benoni & Benko"]),
  lineFromMoves(9, "benoni-benko", "Benoni & Benko — Line 9", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 9.", ["Benoni & Benko"]),
  lineFromMoves(10, "benoni-benko", "Benoni & Benko — Line 10", ["d4","Nf6","c4","g6","Nf3","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5","e4","c6","Re1","Re8","h3","exd4","Nxd4","Nc5"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 10.", ["Benoni & Benko"]),
  lineFromMoves(11, "benoni-benko", "Benoni & Benko — Line 11", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","h3","Nf6"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 11.", ["Benoni & Benko"]),
  lineFromMoves(12, "benoni-benko", "Benoni & Benko — Line 12", ["d4","Nf6","Nf3","g6","c4","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 12.", ["Benoni & Benko"]),
  lineFromMoves(13, "benoni-benko", "Benoni & Benko — Line 13", ["d4","Nf6","c4","g6","Nf3","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5","e4","c6"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 13.", ["Benoni & Benko"]),
  lineFromMoves(14, "benoni-benko", "Benoni & Benko — Line 14", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","Qd2","Nf6"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 14.", ["Benoni & Benko"]),
  lineFromMoves(15, "benoni-benko", "Benoni & Benko — Line 15", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","g4","fxg4"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 15.", ["Benoni & Benko"]),
  lineFromMoves(16, "benoni-benko", "Benoni & Benko — Line 16", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f4","O-O","Nf3","c5","d5","e6","Be2","exd5","cxd5","Re8"], "Surprise d4 defenses — Modern Benoni ...c5 and Benko ...b5 with clear pawn-break plans. Line 16.", ["Benoni & Benko"]),
];
