import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu.";

/** Potluck course — generated from validated templates. */
export default [
  lineFromMoves(1, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 1", ["e4","Nf6","e5","Nd5","d4","d6","c4","Nb6","f4","dxe5","fxe5","Nc6","Be3","Bf5","Nc3","e6","Nf3","Bb4"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 1.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(2, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 2", ["e4","Nf6","e5","Nd5","d4","d6","c4","Nb6","f4","dxe5","fxe5","Nc6","Be3","Bf5","Nc3","e6","Nf3","Be7"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 2.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(3, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 3", ["e4","Nf6","Nc3","d5","e5","Ne4","Nxe4","dxe4","d3","exd3","Bxd3","e6","Nf3","c5","O-O","Nc6"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 3.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(4, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 4", ["e4","Nf6","e5","Nd5","c4","Nb6","c5","Nd5","d4","e6","Nf3","c6","Be2","Be7","O-O","O-O"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 4.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(5, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 5", ["e4","Nf6","e5","Nd5","d4","d6","Nf3","g6","Bc4","Nb6","Bb3","Bg7","a4","a5","O-O","O-O"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 5.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(6, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 6", ["e4","Nf6","e5","Nd5","d4","d6","Nf3","g6","Be2","Bg7","O-O","O-O","c4","Nb6","Nc3","c5"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 6.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(7, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 7", ["e4","Nf6","e5","Nd5","d4","d6","Bc4","Nb6","Bb3","Bf5","Nf3","e6","O-O","Be7","Re1","O-O"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 7.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(8, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 8", ["e4","Nf6","e5","Nd5","d4","d6","f4","g6","Nf3","Bg7","Be2","O-O","O-O","c5","c4","Nb6"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 8.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(9, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 9", ["e4","Nf6","e5","Nd5","d4","d6","Nf3","Bg4","Be2","e6","O-O","Be7","c4","Nb6","Nc3","O-O"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 9.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(10, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 10", ["e4","Nf6","e5","Nd5","d4","d6","Nf3","g6","c4","Nb6","Be2","Bg7","O-O","O-O","Nc3","c5"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 10.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(11, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 11", ["e4","Nf6","e5","Nd5","d4","d6","Nf3","g6","Be2","Bg7","O-O","O-O","c4","Nb6","Nc3","c5","dxc5","dxc5"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 11.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(12, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 12", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 12.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(13, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 13", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f3","O-O","Be3","c5","d5","e6","Qd2","exd5","cxd5","a6"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 13.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(14, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 14", ["d4","Nf6","c4","g6","Nf3","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 14.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(15, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 15", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f4","O-O","Nf3","c5","d5","e6","Be2","exd5"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 15.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(16, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 16", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","g4","Nf6"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 16.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(17, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 17", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 17.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(18, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 18", ["d4","Nf6","c4","g6","Nf3","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5","e4","c6","Re1","Re8","h3","exd4","Nxd4","Nc5"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 18.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(19, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 19", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","h3","Nf6"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 19.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(20, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 20", ["d4","Nf6","Nf3","g6","c4","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 20.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(21, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 21", ["d4","Nf6","c4","g6","Nf3","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5","e4","c6"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 21.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(22, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 22", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","Qd2","Nf6"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 22.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(23, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 23", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","g4","fxg4"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 23.", ["Full Black Rep with 1...Nf6"]),
  lineFromMoves(24, "black-nf6-rep", "Full Black Rep with 1...Nf6 — Line 24", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f4","O-O","Nf3","c5","d5","e6","Be2","exd5","cxd5","Re8"], "A full black rep defined by 1...Nf6 — Alekhine, KID, and Nimzo-Indian transpositions in one unified menu. Line 24.", ["Full Black Rep with 1...Nf6"]),
];
