import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "Scotch with ...Qb6 poison — separate from generic Scotch variations, built for club players.";

/** Potluck course — P1 community-demand batch. */
export default [
  lineFromMoves(1, "blumenfeld-scotch", "Blumenfeld Scotch — Line 1", ["e4","e5","Nf3","Nc6","d4","exd4","Nxd4","Nf6","Nxc6","bxc6","e5","Qe7","Be2","Ng4","O-O","d5"], "Scotch with ...Qb6 poison — separate from generic Scotch variations, built for club players. Line 1.", ["Blumenfeld Scotch"]),
  lineFromMoves(2, "blumenfeld-scotch", "Blumenfeld Scotch — Line 2", ["e4","e5","Nf3","Nc6","d4","exd4","Nxd4","Qh4","Nc3","Bb4","Be2","Nf6","Nf5","Qh5","g4","Nxg4"], "Scotch with ...Qb6 poison — separate from generic Scotch variations, built for club players. Line 2.", ["Blumenfeld Scotch"]),
  lineFromMoves(3, "blumenfeld-scotch", "Blumenfeld Scotch — Line 3", ["e4","e5","Nf3","Nc6","d4","exd4","Nxd4","Bc5","Be3","Qf6","c3","Nge7","Bc4","d6","O-O","O-O"], "Scotch with ...Qb6 poison — separate from generic Scotch variations, built for club players. Line 3.", ["Blumenfeld Scotch"]),
  lineFromMoves(4, "blumenfeld-scotch", "Blumenfeld Scotch — Line 4", ["e4","e5","Nf3","Nc6","d4","Rb8","Nbd2","Nge7","c4","b5","c5","Rg8","a4","Nb4","Nb1","Bb7","Bd3","Rh8"], "Scotch with ...Qb6 poison — separate from generic Scotch variations, built for club players. Line 4.", ["Blumenfeld Scotch"]),
  lineFromMoves(5, "blumenfeld-scotch", "Blumenfeld Scotch — Line 5", ["e4","e5","Nf3","Nc6","d4","Qe7","Bd2","Qe6","Qe2","Qh6","d5","Nf6","dxc6","Qxd2+","Nfxd2","Kd8","Qf3","Bb4"], "Scotch with ...Qb6 poison — separate from generic Scotch variations, built for club players. Line 5.", ["Blumenfeld Scotch"]),
  lineFromMoves(6, "blumenfeld-scotch", "Blumenfeld Scotch — Line 6", ["e4","e5","Nf3","Nc6","d4","Qf6","Be3","Ke7","Nc3","Qh4","b4","Kd8","Qd2","Qg4","Bc4","Qxf3","Qd3","Qf6"], "Scotch with ...Qb6 poison — separate from generic Scotch variations, built for club players. Line 6.", ["Blumenfeld Scotch"]),
  lineFromMoves(7, "blumenfeld-scotch", "Blumenfeld Scotch — Line 7", ["e4","e5","Nf3","Nc6","d4","Qg5","Qd2","Qh4","Kd1","Qe7","Na3","Nf6","Ke1","h5","Nb5","exd4","Qc3","Qd6"], "Scotch with ...Qb6 poison — separate from generic Scotch variations, built for club players. Line 7.", ["Blumenfeld Scotch"]),
  lineFromMoves(8, "blumenfeld-scotch", "Blumenfeld Scotch — Line 8", ["e4","e5","Nf3","Nc6","d4","Qh4","Qd2","Qh3","Be2","Qxf3","Kf1","h6","Qb4","Qxe4","f4","Qxd4","Qxf8+","Kxf8"], "Scotch with ...Qb6 poison — separate from generic Scotch variations, built for club players. Line 8.", ["Blumenfeld Scotch"]),
  lineFromMoves(9, "blumenfeld-scotch", "Blumenfeld Scotch — Line 9", ["e4","e5","Nf3","Nc6","d4","Ke7","Bh6","d6","Nc3","Bg4","b3","Na5","Rb1","Bc8","Rc1","Nxh6","Nb5","g6"], "Scotch with ...Qb6 poison — separate from generic Scotch variations, built for club players. Line 9.", ["Blumenfeld Scotch"]),
  lineFromMoves(10, "blumenfeld-scotch", "Blumenfeld Scotch — Line 10", ["e4","e5","Nf3","Nc6","d4","Be7","Qd2","h5","Kd1","Kf8","Ke1","d6","dxe5","Nh6","g4","Bf5","g5","Bc8"], "Scotch with ...Qb6 poison — separate from generic Scotch variations, built for club players. Line 10.", ["Blumenfeld Scotch"]),
  lineFromMoves(11, "blumenfeld-scotch", "Blumenfeld Scotch — Line 11", ["e4","e5","Nf3","Nc6","d4","Bd6","Qd3","Nb8","c4","Kf8","Bh6","Qh4","Kd1","Qf4","Qa3","Nxh6","h3","Qh2"], "Scotch with ...Qb6 poison — separate from generic Scotch variations, built for club players. Line 11.", ["Blumenfeld Scotch"]),
  lineFromMoves(12, "blumenfeld-scotch", "Blumenfeld Scotch — Line 12", ["e4","e5","Nf3","Nc6","d4","Bc5","Qd2","b5","Be2","d5","h3","Bb6","Nc3","Qe7","exd5","g6","Rg1","Bxd4"], "Scotch with ...Qb6 poison — separate from generic Scotch variations, built for club players. Line 12.", ["Blumenfeld Scotch"]),
  lineFromMoves(13, "blumenfeld-scotch", "Blumenfeld Scotch — Line 13", ["e4","e5","Nf3","Nc6","d4","Bb4+","c3","f6","Bc4","b6","cxb4","Nxb4","Bf1","Ne7","a4","h6","h4","Nd3+"], "Scotch with ...Qb6 poison — separate from generic Scotch variations, built for club players. Line 13.", ["Blumenfeld Scotch"]),
  lineFromMoves(14, "blumenfeld-scotch", "Blumenfeld Scotch — Line 14", ["e4","e5","Nf3","Nc6","d4","Ba3","Bd3","f5","Bh6","Nb4","Nc3","Kf8","Be2","d5","g3","Nf6","Qd3","Qd7"], "Scotch with ...Qb6 poison — separate from generic Scotch variations, built for club players. Line 14.", ["Blumenfeld Scotch"]),
];
