import { mkLine, lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION =
  "The Caro-Kann Defense: 1.e4 c6 — twenty-eight solid lines with ...d5, a safe king, and flexible pawn structures.";

export default [
  mkLine(
    1,
    "caro_main",
    "Main Line — Classical ...Bf5",
    "Line #1 · Classical Caro",
    "The classical Caro gives you ...d5 and ...Bf5 — simple and strong.",
    ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5","Ng3","Bg6","Nf3","Nd7","h4","h6","Bd3","Bxd3","Qxd3","Qc7"],
    [
      "e4.",
      "...c6 — Caro-Kann!",
      "d4.",
      "...d5 — challenge the center.",
      "Nc3.",
      "...dxe4 trade.",
      "Nxe4.",
      "...Bf5 — classical!",
      "Ng3.",
      "...Bg6 — bishop safe.",
      "Nf3.",
      "...Nd7 — flexible.",
      "h4.",
      "...h6 — stop h5.",
      "Bd3.",
      "...Bxd3 trade.",
      "Qxd3.",
      "...Qc7 — connect rooks.",
    ],
    ["Caro-Kann","Classical"]
  ),
  mkLine(
    2,
    "caro_advance",
    "Advance — ...c5 Break",
    "Line #2 · Advance variation",
    "White pushes e5? Your ...c5 break is the thematic response.",
    ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","cxd4","cxd4","Rc8"],
    [
      "e4.",
      "...c6.",
      "d4.",
      "...d5.",
      "e5.",
      "...Bf5 — best!",
      "Nf3.",
      "...e6 — support d5.",
      "Be2.",
      "...c5! — break.",
      "O-O.",
      "...Nc6.",
      "c3.",
      "...Qb6 — hit b2.",
      "Na3.",
      "...cxd4.",
      "cxd4.",
      "...Rc8 — pressure c-file.",
    ],
    ["Caro-Kann","Advance"]
  ),
  lineFromMoves(3, "caro-kann", "Exchange 3.exd5", ["e4","c6","d4","d5","exd5","cxd5","Bd3","Nc6","c3","Nf6","Bf4","Bg4","Qb3","Qd7"], "Exchange Caro — develop with ...Nc6.", ["Caro-Kann"]),
  lineFromMoves(4, "caro-kann", "Panov 3.exd5 cxd5", ["e4","c6","d4","d5","exd5","cxd5","c4","Nf6","Nc3","e6","Nf3","Be7","cxd5","Nxd5"], "Panov Attack — IQP for White, solid for you.", ["Caro-Kann"]),
  mkLine(
    5,
    "caro_modern",
    "Modern — ...g6",
    "Line #5 · Modern Caro",
    "The modern ...g6 and ...Bg7 is flexible and trendy.",
    ["e4","c6","d4","d5","Nc3","g6","Nf3","Bg7","h3","e6","Bd3","Ne7","O-O","O-O","Re1","Nd7","Bf4","f6"],
    [
      "e4.",
      "...c6.",
      "d4.",
      "...d5.",
      "Nc3.",
      "...g6 — modern!",
      "Nf3.",
      "...Bg7 fianchetto.",
      "h3.",
      "...e6.",
      "Bd3.",
      "...Ne7 — reroute.",
      "O-O.",
      "...O-O.",
      "Re1.",
      "...Nd7.",
      "Bf4.",
      "...f6 — support e5.",
    ],
    ["Caro-Kann","Modern"]
  ),
  lineFromMoves(6, "caro-kann", "Two Knights 3.Nc3", ["e4","c6","Nc3","d5","Nf3","Bg4","h3","Bxf3","Qxf3","e6","d4","Nf6","Bd3","Be7"], "Two Knights with ...Bg4 pin.", ["Caro-Kann"]),
  lineFromMoves(7, "caro-kann", "Fantasy 3.f3", ["e4","c6","f3","d5","d4","e6","Nc3","dxe4","fxe4","f5","Nf3","fxe4","Nxe4","Nf6"], "Fantasy variation — counter with ...f5.", ["Caro-Kann"]),
  mkLine(
    8,
    "caro_g4",
    "Advance ...g4 — Short System",
    "Line #8 · ...g4 push",
    "In the Advance, ...g4 kicks the knight and gains space.",
    ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","O-O-O","Nb5","Re8"],
    [
      "e4.",
      "...c6.",
      "d4.",
      "...d5.",
      "e5.",
      "...Bf5.",
      "Nf3.",
      "...e6.",
      "Be2.",
      "...c5.",
      "O-O.",
      "...Nc6.",
      "c3.",
      "...Qb6.",
      "Na3.",
      "...g4! — Short system.",
      "Nh4.",
      "...Be4 — bishop strong.",
    ],
    ["Caro-Kann","Advance"]
  ),
  lineFromMoves(9, "caro-kann", "Classical 6.h4", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5","Ng3","Bg6","Nf3","Nd7","h4","h6","Bd3","Bxd3","Qxd3","Qc7"], "h4 line — full classical.", ["Caro-Kann"]),
  lineFromMoves(10, "caro-kann", "4...Nd7 Classical", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Nd7","Ng5","Ngf6","Bd3","e6","N1f3","Be7","O-O","O-O"], "4...Nd7 — solid classical.", ["Caro-Kann"]),
  lineFromMoves(11, "caro-kann", "Advance 5...c5", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","cxd4"], "Advance c5 break — core plan.", ["Caro-Kann"]),
  lineFromMoves(12, "caro-kann", "3.Nd2 Tarrasch", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5","Nd6+","Qxd6","Bd2","Nd7","Bc3","O-O-O"], "Tarrasch Nd2 — same ...Bg4.", ["Caro-Kann"]),
  mkLine(
    13,
    "caro_karpov",
    "Karpov — ...Nd7 and ...e6",
    "Line #13 · Karpov setup",
    "Karpov's ...Nd7 and ...e6 is the gold standard of solid.",
    ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Nd7","Nf3","Ngf6","Nxf6+","Nxf6","Bd3","e6","O-O","Bd6","Re1","O-O","c4","Re8"],
    [
      "e4.",
      "...c6.",
      "d4.",
      "...d5.",
      "Nc3.",
      "...dxe4.",
      "Nxe4.",
      "...Nd7 — Karpov.",
      "Nf3.",
      "...Ngf6.",
      "Nxf6+.",
      "...Nxf6 recapture.",
      "Bd3.",
      "...e6.",
      "O-O.",
      "...Bd6.",
      "Re1.",
      "...O-O.",
      "c4.",
      "...Re8.",
    ],
    ["Caro-Kann","Karpov"]
  ),
  lineFromMoves(14, "caro-kann", "4.Ng5 Two Knights", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nd7","Ng5","Be7","Nxe6","Nh6"], "Ng5 Two Knights — ...h6 and trade.", ["Caro-Kann"]),
  lineFromMoves(15, "caro-kann", "Advance 7.b6", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","a6"], "Advance Qb6 — prep b5.", ["Caro-Kann"]),
  lineFromMoves(16, "caro-kann", "Exchange 4.c4", ["e4","c6","d4","d5","exd5","cxd5","c4","Nf6","Nc3","e6","Nf3","Be7","cxd5","Nxd5"], "Exchange c4 — IQP game.", ["Caro-Kann"]),
  lineFromMoves(17, "caro-kann", "Modern 7...f6", ["e4","c6","d4","d5","Nc3","g6","Nf3","Bg7","h3","e6","Bd3","Ne7","O-O","O-O","Re1","Nd7","Bf4","f6"], "Modern f6 — support e5 break.", ["Caro-Kann"]),
  mkLine(
    18,
    "caro_bronstein",
    "Bronstein-Larsen — ...g6",
    "Line #18 · Bronstein-Larsen",
    "The Bronstein-Larsen with early ...g6 is sharp and fun.",
    ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Nf6","Nxf6+","gxf6","c3","Bg7","Bd3","e5","Qh5","Qe7","Nf3","f5"],
    [
      "e4.",
      "...c6.",
      "d4.",
      "...d5.",
      "Nc3.",
      "...dxe4.",
      "Nxe4.",
      "...Nf6.",
      "Nxf6+.",
      "...gxf6 — Bronstein!",
      "c3.",
      "...Bg7.",
      "Bd3.",
      "...e5! — central break.",
      "Qh5.",
      "...Qe7.",
      "Nf3.",
      "...f5 — kingside space.",
    ],
    ["Caro-Kann","Bronstein-Larsen"]
  ),
  lineFromMoves(19, "caro-kann", "Advance 6...Na6", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","O-O-O"], "Na6 reroute in Advance.", ["Caro-Kann"]),
  lineFromMoves(20, "caro-kann", "Classical 8...Qc7", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5","Ng3","Bg6","Nf3","Nd7","h4","h6","Bd3","Bxd3","Qxd3","Qc7"], "Qc7 classical — connect rooks.", ["Caro-Kann"]),
  lineFromMoves(21, "caro-kann", "4.Bc4 Aggressive", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5","Bc4","e6","Ng5","Bg6","N1f3","h6","Nh4","Nd7"], "Bc4 aggressive — trade bishops.", ["Caro-Kann"]),
  lineFromMoves(22, "caro-kann", "Panov 5...e6", ["e4","c6","d4","d5","exd5","cxd5","c4","Nf6","Nc3","e6","Nf3","Be7","cxd5","Nxd5","Bd3","Nc6"], "Panov e6 — solid development.", ["Caro-Kann"]),
  lineFromMoves(23, "caro-kann", "Advance 8...Be4", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","O-O-O","Nb5","Re8"], "Be4 Short system — strong bishop.", ["Caro-Kann"]),
  lineFromMoves(24, "caro-kann", "3.e5 Advance Early", ["e4","c6","e5","d5","d4","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6"], "Early e5 Advance — same plans.", ["Caro-Kann"]),
  mkLine(
    25,
    "caro_gurgenidze",
    "Gurgenidze — ...g6 and ...Bg7",
    "Line #25 · Gurgenidze system",
    "Gurgenidze combines ...g6 with solid center play.",
    ["e4","c6","d4","d5","Nc3","g6","Nf3","Bg7","Be2","e6","O-O","Ne7","Bf4","O-O","Qd2","b5","a3","a5"],
    [
      "e4.",
      "...c6.",
      "d4.",
      "...d5.",
      "Nc3.",
      "...g6.",
      "Nf3.",
      "...Bg7.",
      "Be2.",
      "...e6.",
      "O-O.",
      "...Ne7.",
      "Bf4.",
      "...O-O.",
      "Qd2.",
      "...b5 — queenside expansion.",
      "a3.",
      "...a5.",
    ],
    ["Caro-Kann","Gurgenidze"]
  ),
  lineFromMoves(26, "caro-kann", "Two Knights 4.Bc4", ["e4","c6","Nc3","d5","Nf3","Bg4","h3","Bxf3","Qxf3","e6","d4","Nf6","Bd3","Be7","O-O","O-O"], "Two Knights Bc4 — normal development.", ["Caro-Kann"]),
  lineFromMoves(27, "caro-kann", "Classical 9...O-O-O", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5","Ng3","Bg6","Nf3","Nd7","h4","h6","Bd3","Bxd3","Qxd3","Qc7","O-O","O-O-O"], "Long castle in classical — counterplay.", ["Caro-Kann"]),
  lineFromMoves(28, "caro-kann", "Fortress Karpov", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Nd7","Nf3","Ngf6","Nxf6+","Nxf6","Bd3","e6","O-O","Bd6","Re1","O-O","c4","Re8"], "Full Karpov fortress — rock solid.", ["Caro-Kann"]),
];
