import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines.";

/** Potluck course — generated from validated templates. */
export default [
  lineFromMoves(1, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 1", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5","Ng3","Bg6","Nf3","Nd7","h4","h6","Bd3","Bxd3","Qxd3","Qc7"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 1.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(2, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 2", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","cxd4","cxd4","Rc8"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 2.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(3, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 3", ["e4","c6","d4","d5","exd5","cxd5","Bd3","Nc6","c3","Nf6","Bf4","Bg4","Qb3","Qd7"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 3.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(4, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 4", ["e4","c6","d4","d5","exd5","cxd5","c4","Nf6","Nc3","e6","Nf3","Be7","cxd5","Nxd5"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 4.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(5, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 5", ["e4","c6","d4","d5","Nc3","g6","Nf3","Bg7","h3","e6","Bd3","Ne7","O-O","O-O","Re1","Nd7","Bf4","f6"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 5.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(6, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 6", ["e4","c6","Nc3","d5","Nf3","Bg4","h3","Bxf3","Qxf3","e6","d4","Nf6","Bd3","Be7"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 6.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(7, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 7", ["e4","c6","f3","d5","d4","e6","Nc3","dxe4","fxe4","f5","Nf3","fxe4","Nxe4","Nf6"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 7.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(8, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 8", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","O-O-O","Nb5","Re8"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 8.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(9, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 9", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Nd7","Ng5","Ngf6","Bd3","e6","N1f3","Be7","O-O","O-O"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 9.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(10, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 10", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","cxd4"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 10.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(11, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 11", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5","Nd6+","Qxd6","Bd2","Nd7","Bc3","O-O-O"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 11.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(12, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 12", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Nd7","Nf3","Ngf6","Nxf6+","Nxf6","Bd3","e6","O-O","Bd6","Re1","O-O","c4","Re8"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 12.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(13, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 13", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nd7","Ng5","Be7","Nxe6","Nh6"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 13.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(14, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 14", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","a6"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 14.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(15, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 15", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Nf6","Nxf6+","gxf6","c3","Bg7","Bd3","e5","Qh5","Qe7","Nf3","f5"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 15.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(16, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 16", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","O-O-O"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 16.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(17, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 17", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5","Bc4","e6","Ng5","Bg6","N1f3","h6","Nh4","Nd7"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 17.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(18, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 18", ["e4","c6","d4","d5","exd5","cxd5","c4","Nf6","Nc3","e6","Nf3","Be7","cxd5","Nxd5","Bd3","Nc6"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 18.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(19, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 19", ["e4","c6","e5","d5","d4","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 19.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(20, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 20", ["e4","c6","d4","d5","Nc3","g6","Nf3","Bg7","Be2","e6","O-O","Ne7","Bf4","O-O","Qd2","b5","a3","a5"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 20.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(21, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 21", ["e4","c6","Nc3","d5","Nf3","Bg4","h3","Bxf3","Qxf3","e6","d4","Nf6","Bd3","Be7","O-O","O-O"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 21.", ["Learn the ENTIRE Caro-Kann!"]),
  lineFromMoves(22, "caro-full", "Learn the ENTIRE Caro-Kann! — Line 22", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5","Ng3","Bg6","Nf3","Nd7","h4","h6","Bd3","Bxd3","Qxd3","Qc7","O-O","O-O-O"], "Far more in depth than the base Caro course — Classical, Advance, and Fantasy lines. Line 22.", ["Learn the ENTIRE Caro-Kann!"]),
];
