import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup.";

/** Potluck course — P1 community-demand batch. */
export default [
  lineFromMoves(1, "dutch-defense", "Dutch Defense — Line 1", ["d4","f5","c4","Nf6","g3","e6","Bg2","Be7","Nf3","O-O","O-O","d6","Nc3","Qe8"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 1.", ["Dutch Defense"]),
  lineFromMoves(2, "dutch-defense", "Dutch Defense — Line 2", ["d4","f5","c4","e6","Nf3","Nf6","g3","d5","Bg2","c6","O-O","Bd6","b3","O-O"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 2.", ["Dutch Defense"]),
  lineFromMoves(3, "dutch-defense", "Dutch Defense — Line 3", ["d4","f5","g3","Nf6","Bg2","g6","Nf3","Bg7","O-O","O-O","c4","d6","Nc3","Qe8"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 3.", ["Dutch Defense"]),
  lineFromMoves(4, "dutch-defense", "Dutch Defense — Line 4", ["d4","f5","Nf3","Nf6","c4","e6","g3","Be7","Bg2","O-O","O-O","d6","Nc3","Qe8"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 4.", ["Dutch Defense"]),
  lineFromMoves(5, "dutch-defense", "Dutch Defense — Line 5", ["d4","f5","c4","Nf6","Nc3","e6","a3","Be7","Nf3","O-O","e3","d6","Be2","Qe8"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 5.", ["Dutch Defense"]),
  lineFromMoves(6, "dutch-defense", "Dutch Defense — Line 6", ["c4","Nc6","d3","a6","f4","Nb8","a3","f5","b3","b6","Nc3","d5","b4","Qd6","Kf2","g6","d4","Kd7"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 6.", ["Dutch Defense"]),
  lineFromMoves(7, "dutch-defense", "Dutch Defense — Line 7", ["c4","Na6","d4","d5","f3","Qd6","Qc2","Bh3","Qf5","f6","Na3","Bxf5","h3","Qb4+","Kf2","Bg4","c5","b5"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 7.", ["Dutch Defense"]),
  lineFromMoves(8, "dutch-defense", "Dutch Defense — Line 8", ["c4","Nh6","e3","d6","g4","a5","Ne2","g5","Rg1","b6","d4","f5","Qc2","c5","Rg2","Nc6","f4","Kd7"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 8.", ["Dutch Defense"]),
  lineFromMoves(9, "dutch-defense", "Dutch Defense — Line 9", ["c4","Nf6","e4","b5","f4","Nh5","Qf3","g6","Qd1","bxc4","Qa4","e5","Kf2","Bb7","h3","Be7","Qc6","f6"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 9.", ["Dutch Defense"]),
  lineFromMoves(10, "dutch-defense", "Dutch Defense — Line 10", ["c4","a6","f3","f5","e3","h6","h3","b6","b4","d5","d4","Be6","Rh2","Rh7","Rh1","Qc8","Qe2","Nd7"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 10.", ["Dutch Defense"]),
  lineFromMoves(11, "dutch-defense", "Dutch Defense — Line 11", ["c4","a5","f4","d6","d3","Bg4","Na3","Na6","e3","Bf3","Be2","e5","b3","Be7","g4","Nb4","Rb1","Bxg4"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 11.", ["Dutch Defense"]),
  lineFromMoves(12, "dutch-defense", "Dutch Defense — Line 12", ["c4","b6","g3","d5","cxd5","Bg4","b3","Nf6","e3","Qd7","Be2","Qd8","Nh3","Nh5","Bb2","e5","Bd3","Qg5"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 12.", ["Dutch Defense"]),
  lineFromMoves(13, "dutch-defense", "Dutch Defense — Line 13", ["c4","b5","f4","d6","b3","Bh3","e4","h6","Bb2","Nf6","Bd3","d5","Qe2","a6","Ba3","h5","Qe3","Bg4"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 13.", ["Dutch Defense"]),
  lineFromMoves(14, "dutch-defense", "Dutch Defense — Line 14", ["c4","c6","h3","e5","g3","Qf6","e4","Be7","Ke2","c5","Bg2","Qb6","h4","Kd8","f4","f6","Ke1","g6"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 14.", ["Dutch Defense"]),
  lineFromMoves(15, "dutch-defense", "Dutch Defense — Line 15", ["c4","c5","Nc3","e5","Nb5","a6","e3","Nc6","Qf3","Bd6","Qf5","h6","Qf4","g5","e4","Na7","Nc7+","Qxc7"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 15.", ["Dutch Defense"]),
  lineFromMoves(16, "dutch-defense", "Dutch Defense — Line 16", ["c4","d6","Na3","Bd7","f4","Bf5","h3","a5","Kf2","c6","b3","h5","Bb2","Rh6","Bd4","Ra6","Qb1","Qc8"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 16.", ["Dutch Defense"]),
  lineFromMoves(17, "dutch-defense", "Dutch Defense — Line 17", ["c4","d5","h4","Nd7","b4","Ngf6","Qc2","Ng8","Bb2","Ndf6","Qa4+","c6","Na3","Ne4","Bxg7","b5","Qd1","Bh3"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 17.", ["Dutch Defense"]),
  lineFromMoves(18, "dutch-defense", "Dutch Defense — Line 18", ["c4","e6","Qc2","e5","g4","Bc5","b3","Qf6","e3","c6","Qe4","Kd8","Bd3","h6","Qd5","Be7","Nh3","Qh4"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 18.", ["Dutch Defense"]),
  lineFromMoves(19, "dutch-defense", "Dutch Defense — Line 19", ["c4","e5","Qb3","Nc6","a4","Qh4","a5","Nh6","a6","d6","Qa4","Qd4","Qa3","Kd8","c5","Qa4","b3","b5"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 19.", ["Dutch Defense"]),
  lineFromMoves(20, "dutch-defense", "Dutch Defense — Line 20", ["c4","f6","Qa4","e6","g3","Be7","Bh3","c6","Qb3","Nh6","Qf3","Ba3","Bf5","Kf8","h3","Nf7","Qe3","g5"], "Full Dutch — Leningrad ...g6, Stonewall ...e6, and Classical ...Nf6 plans vs every white setup. Line 20.", ["Dutch Defense"]),
];
