import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "Covers when the Englund goes wrong and how to keep the attack alive.";

/** Potluck course — generated from validated templates. */
export default [
  lineFromMoves(1, "englund-deep", "Englund Gambit — What They Don't Teach — Line 1", ["d4","e5","dxe5","Nc6","Nf3","Qe7","Bf4","Qb4+","Bd2","Qxb2","Nc3","Bb4","Rb1","Qa3"], "Covers when the Englund goes wrong and how to keep the attack alive. Line 1.", ["Englund Gambit — What They Don't Teach"]),
  lineFromMoves(2, "englund-deep", "Englund Gambit — What They Don't Teach — Line 2", ["d4","e5","dxe5","Nc6","Nf3","Qh4+","g3","Qe4","Nc3","Bb4","Bd2","Bxc3","Bxc3","Qxe5+"], "Covers when the Englund goes wrong and how to keep the attack alive. Line 2.", ["Englund Gambit — What They Don't Teach"]),
  lineFromMoves(3, "englund-deep", "Englund Gambit — What They Don't Teach — Line 3", ["d4","e5","e3","Nc6","c4","d6","Nc3","Nf6","Nf3","Be7","Be2","O-O"], "Covers when the Englund goes wrong and how to keep the attack alive. Line 3.", ["Englund Gambit — What They Don't Teach"]),
  lineFromMoves(4, "englund-deep", "Englund Gambit — What They Don't Teach — Line 4", ["d4","e5","dxe5","Nc6","Nf3","Qe7","Bf4","Qb4+","Bd2","Qxb2","Nd4","Be7"], "Covers when the Englund goes wrong and how to keep the attack alive. Line 4.", ["Englund Gambit — What They Don't Teach"]),
  lineFromMoves(5, "englund-deep", "Englund Gambit — What They Don't Teach — Line 5", ["d4","e5","dxe5","Nc6","Nf3","Qh4","g3","Qe4","Nd4","Be7","Nxc6","Nh6","Nxe7","Ng8"], "Covers when the Englund goes wrong and how to keep the attack alive. Line 5.", ["Englund Gambit — What They Don't Teach"]),
  lineFromMoves(6, "englund-deep", "Englund Gambit — What They Don't Teach — Line 6", ["d4","e5","c4","Nc6","Nc3","Nf6","Nf3","Bb4","Nxe5","O-O","Nxc6","Ne8","Nxd8","Nf6"], "Covers when the Englund goes wrong and how to keep the attack alive. Line 6.", ["Englund Gambit — What They Don't Teach"]),
  lineFromMoves(7, "englund-deep", "Englund Gambit — What They Don't Teach — Line 7", ["d4","e5","dxe5","Nc6","Nf3","Qe7","Bf4","Qb4+","Bd2","Qxb2","Nd4","Be7","Nxc6","Nh6"], "Covers when the Englund goes wrong and how to keep the attack alive. Line 7.", ["Englund Gambit — What They Don't Teach"]),
  lineFromMoves(8, "englund-deep", "Englund Gambit — What They Don't Teach — Line 8", ["d4","e5","c4","Nc6","Nc3","Nf6","Nf3","exd4","Nxd4","Bb4","e3","O-O"], "Covers when the Englund goes wrong and how to keep the attack alive. Line 8.", ["Englund Gambit — What They Don't Teach"]),
  lineFromMoves(9, "englund-deep", "Englund Gambit — What They Don't Teach — Line 9", ["d4","e5","dxe5","Nc6","e4","Nxe5","Nf3","Qe7","Be2","Ng4","O-O","Nxf2"], "Covers when the Englund goes wrong and how to keep the attack alive. Line 9.", ["Englund Gambit — What They Don't Teach"]),
  lineFromMoves(10, "englund-deep", "Englund Gambit — What They Don't Teach — Line 10", ["d4","e5","e4","Nc6","Nf3","d6","Bc4","Nf6","Nc3","Be7","O-O","O-O"], "Covers when the Englund goes wrong and how to keep the attack alive. Line 10.", ["Englund Gambit — What They Don't Teach"]),
  lineFromMoves(11, "englund-deep", "Englund Gambit — What They Don't Teach — Line 11", ["d4","e5","Bf4","Nc6","e3","Nf6","Nd2","Bb4","c3","O-O","Ng1f3","d6"], "Covers when the Englund goes wrong and how to keep the attack alive. Line 11.", ["Englund Gambit — What They Don't Teach"]),
  lineFromMoves(12, "englund-deep", "Englund Gambit — What They Don't Teach — Variation 12", ["d4","e5","dxe5","Nc6","Nf3","Qe7","Bf4","Qb4+","Bd2","Qxb2","Nc3","Bb4","Rb1","Qa3"], "Covers when the Englund goes wrong and how to keep the attack alive. Alternate line 12.", ["Englund Gambit — What They Don't Teach"]),
  lineFromMoves(13, "englund-deep", "Englund Gambit — What They Don't Teach — Variation 13", ["d4","e5","dxe5","Nc6","Nf3","Qe7","Bf4","Qb4+","Bd2","Qxb2","Nc3","Bb4","Rb1","Qa3"], "Covers when the Englund goes wrong and how to keep the attack alive. Alternate line 13.", ["Englund Gambit — What They Don't Teach"]),
  lineFromMoves(14, "englund-deep", "Englund Gambit — What They Don't Teach — Variation 14", ["d4","e5","dxe5","Nc6","Nf3","Qe7","Bf4","Qb4+","Bd2","Qxb2","Nc3","Bb4","Rb1","Qa3"], "Covers when the Englund goes wrong and how to keep the attack alive. Alternate line 14.", ["Englund Gambit — What They Don't Teach"]),
  lineFromMoves(15, "englund-deep", "Englund Gambit — What They Don't Teach — Variation 15", ["d4","e5","dxe5","Nc6","Nf3","Qe7","Bf4","Qb4+","Bd2","Qxb2","Nc3","Bb4","Rb1","Qa3"], "Covers when the Englund goes wrong and how to keep the attack alive. Alternate line 15.", ["Englund Gambit — What They Don't Teach"]),
];
