import { mkLine, lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION =
  "The French Defense: 1.e4 e6 — twenty-six lines building a solid pawn chain and counterattacking on the queenside and in the center.";

export default [
  mkLine(
    1,
    "french_main",
    "Main Line — Advance ...c5",
    "Line #1 · Advance French",
    "White pushes e5? Your ...c5 break is the whole point of the French.",
    ["e4","e6","d4","d5","e5","c5","c3","Nc6","Nf3","Qb6","Be2","cxd4","cxd4","Nh6","Nc3","Nf5","Be3","Qb4"],
    [
      "e4.",
      "...e6 — French!",
      "d4.",
      "...d5 — stake the center.",
      "e5.",
      "...c5! — counterattack.",
      "c3.",
      "...Nc6.",
      "Nf3.",
      "...Qb6 — hit b2!",
      "Be2.",
      "...cxd4.",
      "cxd4.",
      "...Nh6 — knight reroute.",
      "Nc3.",
      "...Nf5 — outpost.",
      "Be3.",
      "...Qb4 — queen active.",
    ],
    ["French Defense","Advance"]
  ),
  mkLine(
    2,
    "french_winawer",
    "Winawer — ...Bb4",
    "Line #2 · Winawer pin",
    "The Winawer with ...Bb4 is sharp and fun.",
    ["e4","e6","d4","d5","Nc3","Bb4","e5","c5","a3","Bxc3+","bxc3","Ne7","Qg4","Qc7","Qxg7","Rg8","Qxh7","cxd4"],
    [
      "e4.",
      "...e6.",
      "d4.",
      "...d5.",
      "Nc3.",
      "...Bb4! — Winawer.",
      "e5.",
      "...c5.",
      "a3.",
      "...Bxc3+ trade.",
      "bxc3.",
      "...Ne7.",
      "Qg4.",
      "...Qc7.",
      "Qxg7.",
      "...Rg8 trap!",
      "Qxh7.",
      "...cxd4 — open center.",
    ],
    ["French Defense","Winawer"]
  ),
  lineFromMoves(3, "french", "Exchange 3.exd5", ["e4","e6","d4","d5","exd5","exd5","Nf3","Nf6","Bd3","Bd6","O-O","O-O","Re1","Re8"], "Exchange French — solid development.", ["French Defense"]),
  lineFromMoves(4, "french", "Tarrasch 3.Nd2", ["e4","e6","d4","d5","Nd2","Nf6","e5","Nfd7","Bd3","c5","c3","Nc6","Ne2","Qb6"], "Tarrasch with Nd2 — ...c5 and ...Qb6.", ["French Defense"]),
  lineFromMoves(5, "french", "Classical — ...Nbd7", ["e4","e6","d4","d5","Nc3","Nf6","e5","Nfd7","f4","c5","Nf3","Nc6","Nxd5","Be7","Nxe7","Ndb8","Nxc8","O-O"], "The classical ...Nbd7 and ...Be7 is rock solid.", ["French Defense","Classical"]),
  lineFromMoves(6, "french", "Rubinstein 3...dxe4", ["e4","e6","d4","d5","Nc3","dxe4","Nxe4","Nd7","Nf3","Ngf6","Nxf6+","Nxf6","Bd3","c5","O-O","Be7"], "Rubinstein — trade on e4.", ["French Defense"]),
  lineFromMoves(7, "french", "King's Indian Attack", ["e4","e6","d3","d5","Nd2","Nf6","Ng1f3","Nbd7","g3","c5","Bg2","Be7","O-O","O-O"], "King's Indian Attack — ...c5 break.", ["French Defense"]),
  mkLine(
    8,
    "french_mc_cutcheon",
    "McCutcheon — ...Bb4xc3",
    "Line #8 · McCutcheon attack",
    "The McCutcheon gives White a weak king — counterattack!",
    ["e4","e6","d4","d5","Nc3","Nf6","Bg5","Bb4","e5","h6","Bd2","Bxc3","bxc3","Ne4","Qg4","g6","Qf3","Qh4+"],
    [
      "e4.",
      "...e6.",
      "d4.",
      "...d5.",
      "Nc3.",
      "...Nf6.",
      "Bg5.",
      "...Bb4! — McCutcheon.",
      "e5.",
      "...h6.",
      "Bd2.",
      "...Bxc3.",
      "bxc3.",
      "...Ne4!",
      "Qg4.",
      "...g6.",
      "Qf3.",
      "...Qh4+ — counter!",
    ],
    ["French Defense","McCutcheon"]
  ),
  lineFromMoves(9, "french", "Advance 6...Nh6", ["e4","e6","d4","d5","e5","c5","c3","Nc6","Nf3","Qb6","Be2","cxd4","cxd4","Nh6","Nc3","Nf5"], "Advance Nh6-Nf5 knight route.", ["French Defense"]),
  lineFromMoves(10, "french", "Steinitz 3.Nc3 Nf6", ["e4","e6","d4","d5","Nc3","Nf6","e5","Nfd7","f4","c5","Nf3","Nc6","Be3","Be7"], "Steinitz with ...Be7.", ["French Defense"]),
  lineFromMoves(11, "french", "Two Knights 3.Nc3 Be7", ["e4","e6","d4","d5","Nc3","Nf6","Bg5","Be7","e5","Nfd7","Bxe7","Qxe7","f4","O-O"], "Two Knights with ...Be7.", ["French Defense"]),
  lineFromMoves(12, "french", "4.c4 Chigorin", ["e4","e6","d4","d5","Nc3","Nf6","Bg5","Bb4","e5","h6","Bd2","Bxc3","bxc3","Ne4","Be3","O-O"], "Chigorin-style c4 plans.", ["French Defense"]),
  lineFromMoves(13, "french", "Kingside ...f6-f5", ["e4","e6","d4","d5","Nc3","Bb4","e5","c5","a3","Bxc3+","bxc3","Ne7","Bb2","O-O","Bc1","Nd7","Bb2","Nf6","Bc1","Bd7"], "Use ...f6 and ...f5 to undermine White's e5 pawn.", ["French Defense"]),
  lineFromMoves(14, "french", "Winawer 7.Qg4", ["e4","e6","d4","d5","Nc3","Bb4","e5","c5","a3","Bxc3+","bxc3","Ne7","Qg4","Qc7","Qxg7","Rg8","Qxh7","cxd4"], "Winawer Qg4 trap — know ...cxd4.", ["French Defense"]),
  lineFromMoves(15, "french", "3.Be3 Sideline", ["e4","e6","d4","d5","Be3","Nf6","Nd2","Nbd7","Ng1f3","Be7","c3","O-O","Bd3","c5"], "Be3 sideline — ...c5 anyway.", ["French Defense"]),
  lineFromMoves(16, "french", "Burn 4.Bd3", ["e4","e6","d4","d5","exd5","exd5","Nf3","Nf6","Bd3","Bd6","O-O","O-O","Bc4","Nbd7"], "Burn variation — trade on e4.", ["French Defense"]),
  lineFromMoves(17, "french", "Advance 7.a3", ["e4","e6","d4","d5","e5","c5","c3","Nc6","Nf3","Qb6","a3","c4","Be2","Na5","Nbd2","Bd7"], "Advance a3 — lock with ...c4.", ["French Defense"]),
  mkLine(
    18,
    "french_qb6",
    "Queen b6 — Hit b2",
    "Line #18 · ...Qb6 pressure",
    "The ...Qb6 move targets b2 and keeps White honest.",
    ["e4","e6","d4","d5","e5","c5","c3","Nc6","Nf3","Qb6","Be2","cxd4","cxd4","Nh6","O-O","Nf5","Nc3","Be7","Re1","O-O"],
    [
      "e4.",
      "...e6.",
      "d4.",
      "...d5.",
      "e5.",
      "...c5!",
      "c3.",
      "...Nc6.",
      "Nf3.",
      "...Qb6!",
      "Be2.",
      "...cxd4.",
      "cxd4.",
      "...Nh6.",
      "O-O.",
      "...Nf5.",
      "Nc3.",
      "...Be7.",
      "Re1.",
      "...O-O.",
    ],
    ["French Defense"]
  ),
  lineFromMoves(19, "french", "Catalan 2.Qe2", ["e4","e6","d4","d5","exd5","exd5","Nf3","Nf6","Bd3","Bd6","O-O","O-O","Bc4","Nbd7"], "Qe2 Catalan-style — normal French.", ["French Defense"]),
  lineFromMoves(20, "french", "4.Nge2 Tarrasch", ["e4","e6","d4","d5","Nd2","Nf6","e5","Nfd7","Bd3","c5","c3","Nc6","Ne2","Qb6","Nf3","Be7"], "Full Tarrasch tabiya.", ["French Defense"]),
  lineFromMoves(21, "french", "5.f4 Classical", ["e4","e6","d4","d5","Nc3","Nf6","e5","Nfd7","f4","c5","Nf3","Nc6","Be3","Be7","Qd2","O-O"], "Classical with ...Be7.", ["French Defense"]),
  lineFromMoves(22, "french", "6.Bd3 Advance", ["e4","e6","d4","d5","e5","c5","c3","Nc6","Nf3","Qb6","Bd3","cxd4","cxd4","Nh6","Nc3","Nf5"], "Bd3 Advance — Nf5 outpost.", ["French Defense"]),
  lineFromMoves(23, "french", "Rubinstein 5.Bd3", ["e4","e6","d4","d5","Nc3","Bb4","e5","c5","a3","Bxc3+","bxc3","Ne7","Ra2","O-O","Rb2","Nd7"], "Rubinstein Bd3 — ...Nc6.", ["French Defense"]),
  lineFromMoves(24, "french", "8...Bd7 Winawer", ["e4","e6","d4","d5","Nc3","Bb4","e5","c5","a3","Bxc3+","bxc3","Ne7","Nf3","Bd7","Bd3","c4","Be2","Ba4"], "Winawer ...Bd7 — lock queenside.", ["French Defense"]),
  lineFromMoves(25, "french", "7.Nb5 Winawer", ["e4","e6","d4","d5","Nc3","Bb4","e5","c5","a3","Bxc3+","bxc3","Ne7","Nf3","Qc7","Bd3","c4","Be2","Nbc6"], "Nb5 Winawer — ...Nbc6.", ["French Defense"]),
  lineFromMoves(26, "french", "Fortress Exchange", ["e4","e6","d4","d5","exd5","exd5","Nf3","Nf6","Bd3","Bd6","O-O","O-O","Re1","Re8","c3","Nbd7"], "Exchange fortress — equal but solid.", ["French Defense"]),
];
