import { mkLine, lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION =
  "Giuoco Piano Greco Gambit — 4.b4! Sacrifice a pawn for open lines and a deadly attack on the f7 square.";

export default [
  mkLine(
    1,
    "greco_main",
    "Accepted — b4 Pawn Sac",
    "Line #1 · Greco core",
    "Black takes on b4? Open the c-file and blast f7 with your bishop and queen.",
    ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","dxc3","Qb3","Qf6","e5","Qg6","Re1","Nge7","Ba3","b5","Qxb5","Rb8","Qa4","Bb6"],
    [
      "e4.",
      "...e5.",
      "Nf3.",
      "...Nc6.",
      "Bc4.",
      "...Bc5 — Giuoco Piano.",
      "b4! — Greco Gambit!",
      "...Bxb4 — they take.",
      "c3 — open the center.",
      "...Ba5 — bishop retreats.",
      "d4! — blast open.",
      "...exd4.",
      "O-O — king safe, rook hits e5.",
      "...dxc3.",
      "Qb3 — double hit on b7 and f7!",
      "...Qf6 — block f7.",
      "e5 — push the queen.",
      "...Qg6.",
      "Re1 — rook joins the attack.",
      "...Nge7.",
      "Ba3 — pin the knight.",
      "...b5.",
      "Qxb5 — grab material.",
      "...Rb8.",
      "Qa4 — queen stays active.",
      "...Bb6.",
    ],
    ["Greco Gambit","Accepted"]
  ),
  lineFromMoves(2, "greco", "5...Ba5 Retreat", ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","dxc3","Qb3","Qf6","e5","Qg6","Re1","Nge7"], "Ba5 retreat — same Qb3 attack.", ["Greco Gambit"]),
  lineFromMoves(3, "greco", "Declined 4...Bb6", ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bb6","b5","Nd4","Nxd4","Bxd4","c3","Bb6","d4","exd4","cxd4","d6","Be3","Nge7","Qd2","O-O","O-O"], "If Black declines, b5 wins space.", ["Greco Gambit","Declined"]),
  lineFromMoves(4, "greco", "7.O-O dxc3", ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","dxc3","Qb3","Qf6","e5","Qg6","Re1"], "O-O before Qb3 — classic Greco.", ["Greco Gambit"]),
  lineFromMoves(5, "greco", "8.Qb3 Qf6", ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","dxc3","Qb3","Qf6","e5","Qg6","Re1","Nge7"], "Qb3 hits b7 and f7.", ["Greco Gambit"]),
  lineFromMoves(6, "greco", "9.e5 Qg6", ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","dxc3","Qb3","Qf6","e5","Qg6","Re1","Nge7","Ba3"], "e5 drives the queen away.", ["Greco Gambit"]),
  lineFromMoves(7, "greco", "10.Re1 Nge7", ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","dxc3","Qb3","Qf6","e5","Qg6","Re1","Nge7","Ba3","b5"], "Re1 adds rook pressure.", ["Greco Gambit"]),
  lineFromMoves(8, "greco", "6...exd4", ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","dxc3","Qb3","Qf6","e5","Qg6","Re1"], "exd4 opens the position.", ["Greco Gambit"]),
  lineFromMoves(9, "greco", "4...Be7 Decline", ["e4","e5","Nf3","Nc6","Bc4","Be7","b4","Nxb4","c3","Nc6","d4","exd4","cxd4","d6","Be3","Nf6","Qd2","O-O","O-O"], "If bishop retreats to e7, b4 still works.", ["Greco Gambit"]),
  lineFromMoves(10, "greco", "5.c3 Ba5", ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","dxc3","Qb3","Qf6","e5","Qg6"], "c3 chases the bishop.", ["Greco Gambit"]),
  lineFromMoves(11, "greco", "11.Ba3 Pin", ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","dxc3","Qb3","Qf6","e5","Qg6","Re1","Nge7","Ba3","b5"], "Ba3 pins the knight on e7.", ["Greco Gambit"]),
  lineFromMoves(12, "greco", "3...Nf6 Two Knights", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","d5","exd5","Na5","Bb5+","c6","dxc6","bxc6","Be2","h6","Nf3","e4","Ne5","Qd4"], "If Black plays ...Nf6, Ng5 is strong.", ["Greco Gambit","Two Knights"]),
  lineFromMoves(13, "greco", "7...dxc3", ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","dxc3","Qb3","Qf6","e5","Qg6","Re1","Nge7"], "Take on c3 — Qb3 follows.", ["Greco Gambit"]),
  lineFromMoves(14, "greco", "8...Qf6 Block", ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","dxc3","Qb3","Qf6","e5","Qg6","Re1","Nge7","Ba3"], "Qf6 blocks f7 — push e5.", ["Greco Gambit"]),
  lineFromMoves(15, "greco", "12.Qxb5 Material", ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","dxc3","Qb3","Qf6","e5","Qg6","Re1","Nge7","Ba3","b5","Qxb5"], "Grab the b-pawn when Black plays ...b5.", ["Greco Gambit"]),
  lineFromMoves(16, "greco", "4.b4 Bxb4", ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","dxc3","Qb3","Qf6","e5","Qg6","Re1","Nge7"], "Core accepted line.", ["Greco Gambit"]),
  lineFromMoves(17, "greco", "6.d4 exd4", ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","dxc3","Qb3","Qf6","e5","Qg6","Re1"], "d4 is the key follow-up.", ["Greco Gambit"]),
  lineFromMoves(18, "greco", "13.Rb8 Qa4", ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4","Bxb4","c3","Ba5","d4","exd4","O-O","dxc3","Qb3","Qf6","e5","Qg6","Re1","Nge7","Ba3","b5","Qxb5","Rb8","Qa4"], "Full line to active queen play.", ["Greco Gambit"]),
];
