import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups.";

/** Potluck course — generated from validated templates. */
export default [
  lineFromMoves(1, "italian-ext", "Italian — Potluck Lines — Line 1", ["e4","e5","Nf3","Nc6","Bc4","Bc5","c3","Nf6","d4","exd4","cxd4","Bb4+","Nc3","Nxe4","O-O","Nxc3","bxc3","Bxc3","Ba3","Bxa1","Re1+","Ne7","Bxe7","Qxe7","Rxe7+","Kxe7","Qxa1"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 1.", ["Italian — Potluck Lines"]),
  lineFromMoves(2, "italian-ext", "Italian — Potluck Lines — Line 2", ["e4","e5","Nf3","Nc6","Bc4","Bc5","c3","Nf6","d4","exd4","cxd4","Bb4+","Nc3","Nxe4","O-O","Nxc3","bxc3","Bxc3","Ba3","d6","Rc1","Ba5","Qa4","O-O","d5","Ne5","Nxe5","dxe5","Qxa5"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 2.", ["Italian — Potluck Lines"]),
  lineFromMoves(3, "italian-ext", "Italian — Potluck Lines — Line 3", ["e4","e5","Nf3","Nc6","Bc4","Bc5","c3","Nf6","d4","exd4","cxd4","Bb4+","Nc3","Nxe4","O-O","Nxc3","bxc3","Bxc3","Ba3","Bb4","Bxb4","Nxb4","Qe1+","Qe7","Qxb4"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 3.", ["Italian — Potluck Lines"]),
  lineFromMoves(4, "italian-ext", "Italian — Potluck Lines — Line 4", ["e4","e5","Nf3","Nc6","Bc4","Bc5","c3","Nf6","d4","exd4","cxd4","Bb6","e5","Ng4","h3","Nh6","d5","Na5","Bg5","f6","exf6"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 4.", ["Italian — Potluck Lines"]),
  lineFromMoves(5, "italian-ext", "Italian — Potluck Lines — Line 5", ["e4","e5","Nf3","Nc6","Bc4","Nf6","d4","Nxe4","dxe5","Bc5","Qd5","Bxf2+","Kf1","O-O","Qxe4"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 5.", ["Italian — Potluck Lines"]),
  lineFromMoves(6, "italian-ext", "Italian — Potluck Lines — Line 6", ["e4","e5","Nf3","Nc6","Bc4","Nf6","d4","exd4","O-O","Nxe4","Re1","d5","Bxd5","Qxd5","Nc3"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 6.", ["Italian — Potluck Lines"]),
  lineFromMoves(7, "italian-ext", "Italian — Potluck Lines — Line 7", ["e4","e5","Nf3","Nc6","Bc4","Bc5","c3","Nf6","d4","exd4","cxd4","Bb4+","Nc3","Nxe4","O-O","Bxc3","d5","Bf6","Re1","Ne7","Rxe4"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 7.", ["Italian — Potluck Lines"]),
  lineFromMoves(8, "italian-ext", "Italian — Potluck Lines — Line 8", ["e4","e5","Nf3","d6","d4","exd4","Nxd4","Nf6","Nc3","Be7","Bf4","O-O","Qd2"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 8.", ["Italian — Potluck Lines"]),
  lineFromMoves(9, "italian-ext", "Italian — Potluck Lines — Line 9", ["e4","e5","Nf3","Nc6","Bc4","Bc5","c3","Nf6","d3","d6","O-O","O-O","Re1"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 9.", ["Italian — Potluck Lines"]),
  lineFromMoves(10, "italian-ext", "Italian — Potluck Lines — Line 10", ["e4","e5","Nf3","Nc6","Bc4","Bc5","c3","Nf6","d4","exd4","cxd4","Bb4+","Nc3","d6","d5","Ne7","O-O","O-O"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 10.", ["Italian — Potluck Lines"]),
  lineFromMoves(11, "italian-ext", "Italian — Potluck Lines — Line 11", ["e4","e5","Nf3","Nc6","Bc4","Bc5","c3","Nf6","d4","exd4","cxd4","Bb4+","Nc3","Nxe4","O-O","Nxc3","bxc3","Bxc3","Be3"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 11.", ["Italian — Potluck Lines"]),
  lineFromMoves(12, "italian-ext", "Italian — Potluck Lines — Line 12", ["e4","e5","Nf3","Nc6","Bc4","Nf6","d4","exd4","e5","Ne4","Bd5"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 12.", ["Italian — Potluck Lines"]),
  lineFromMoves(13, "italian-ext", "Italian — Potluck Lines — Line 13", ["e4","e5","Nf3","Nc6","Bc4","Be7","c3","Nf6","d4","exd4","cxd4","O-O","O-O"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 13.", ["Italian — Potluck Lines"]),
  lineFromMoves(14, "italian-ext", "Italian — Potluck Lines — Line 14", ["e4","e5","Nf3","Nc6","Bc4","Bc5","c3","d6","d4","exd4","cxd4","Bb6","Be3"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 14.", ["Italian — Potluck Lines"]),
  lineFromMoves(15, "italian-ext", "Italian — Potluck Lines — Line 15", ["e4","e5","Nf3","Nc6","Bc4","Bc5","c3","Nf6","d3","a6","O-O","d6","Re1"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 15.", ["Italian — Potluck Lines"]),
  lineFromMoves(16, "italian-ext", "Italian — Potluck Lines — Line 16", ["e4","e5","Nf3","Nc6","Bc4","Nf6","d4","exd4","e5","Ne4","Qe2"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 16.", ["Italian — Potluck Lines"]),
  lineFromMoves(17, "italian-ext", "Italian — Potluck Lines — Line 17", ["e4","e5","Nf3","d6","d4","Nf6","Nc3","Nbd7","Bc4","Be7","O-O","O-O"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 17.", ["Italian — Potluck Lines"]),
  lineFromMoves(18, "italian-ext", "Italian — Potluck Lines — Line 18", ["e4","e5","Nf3","Nc6","Bc4","Qe7","c3","Nf6","d4","exd4","cxd4","d6","O-O","Be6"], "Various Italian Game lines — Giuoco Piano, Evans, and aggressive setups. Line 18.", ["Italian — Potluck Lines"]),
];
