import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more.";

/** Potluck course — generated from validated templates. */
export default [
  lineFromMoves(1, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 1", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 1.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(2, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 2", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f3","O-O","Be3","c5","d5","e6","Qd2","exd5","cxd5","a6"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 2.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(3, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 3", ["d4","Nf6","c4","g6","Nf3","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 3.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(4, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 4", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f4","O-O","Nf3","c5","d5","e6","Be2","exd5"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 4.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(5, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 5", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","g4","Nf6"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 5.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(6, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 6", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 6.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(7, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 7", ["d4","Nf6","c4","g6","Nf3","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5","e4","c6","Re1","Re8","h3","exd4","Nxd4","Nc5"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 7.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(8, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 8", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","h3","Nf6"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 8.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(9, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 9", ["d4","Nf6","Nf3","g6","c4","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 9.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(10, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 10", ["d4","Nf6","c4","g6","Nf3","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5","e4","c6"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 10.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(11, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 11", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","Qd2","Nf6"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 11.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(12, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 12", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","g4","fxg4"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 12.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(13, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 13", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f4","O-O","Nf3","c5","d5","e6","Be2","exd5","cxd5","Re8"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 13.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(14, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 14", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 14.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(15, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 15", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","a5"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 15.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(16, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 16", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","Qd2","Nf6","g4","Nh5"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 16.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(17, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 17", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f3","O-O","Be3","e5","d5","c5","Qd2","a6"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 17.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(18, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 18", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","h3","Nf6","g4","Nh5"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 18.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(19, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 19", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Re1","b6","Bf1","Ba6"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 19.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(20, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 20", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","Qd2","Nf6","g4","fxg4"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 20.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(21, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 21", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","g4","Nf6","h3","Nh5"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 21.", ["Learn the ENTIRE King's Indian!!!"]),
  lineFromMoves(22, "kid-full", "Learn the ENTIRE King's Indian!!! — Line 22", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f4","O-O","Nf3","c5","d5","e6","Be2","exd5","cxd5","Bg4"], "Goes even deeper than the base KID course — Classical, Saemisch, Bayonet, and more. Line 22.", ["Learn the ENTIRE King's Indian!!!"]),
];
