import { mkLine, lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION =
  "The King's Indian Defense: 1.d4 Nf6 2.c4 g6 — thirty-five dynamic lines with ...Bg7, ...d6, and kingside counterattacks.";

export default [
  mkLine(
    1,
    "kid_main",
    "Classical KID — ...O-O",
    "Line #1 · Classical setup",
    "The classical KID: fianchetto, castle, then strike with ...e5 or ...c5.",
    ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5"],
    [
      "d4.",
      "...Nf6 — KID!",
      "c4.",
      "...g6 — fianchetto prep.",
      "Nc3.",
      "...Bg7 — bishop eyes the center.",
      "e4.",
      "...d6 — solid foundation.",
      "Nf3.",
      "...O-O — king safe.",
      "Be2.",
      "...e5! — strike!",
      "O-O.",
      "...Nc6.",
      "d5.",
      "...Ne7 — reroute.",
      "Ne1.",
      "...Nd7.",
      "f3.",
      "...f5 — kingside attack!",
    ],
    ["King's Indian Defense","Classical"]
  ),
  lineFromMoves(2, "kid", "Saemisch — ...c5 Counter", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f3","O-O","Be3","c5","d5","e6","Qd2","exd5","cxd5","a6"], "White plays the Saemisch? Counter on the queenside with ...c5.", ["King's Indian Defense","Saemisch"]),
  lineFromMoves(3, "kid", "Fianchetto 3.Nf3", ["d4","Nf6","c4","g6","Nf3","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5"], "Fianchetto setup — ...e5 break.", ["King's Indian Defense"]),
  lineFromMoves(4, "kid", "Four Pawns 7.f4", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f4","O-O","Nf3","c5","d5","e6","Be2","exd5"], "Four Pawns — ...c5 and ...e6.", ["King's Indian Defense"]),
  lineFromMoves(5, "kid", "Bayonet — b4 Push", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","g4","Nf6"], "White pushes b4? Meet it with ...c6 and ...b5 counterplay.", ["King's Indian Defense","Bayonet"]),
  lineFromMoves(6, "kid", "Averbakh 7.Be2", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7"], "Averbakh with Ne1-Nd7.", ["King's Indian Defense"]),
  lineFromMoves(7, "kid", "Petrosian 7.d5", ["d4","Nf6","c4","g6","Nf3","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5","e4","c6","Re1","Re8","h3","exd4","Nxd4","Nc5"], "Petrosian d5 — ...f5 break.", ["King's Indian Defense"]),
  lineFromMoves(8, "kid", "Classical ...f5", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","h3","Nf6"], "The ...f5 break is your main kingside weapon in the classical KID.", ["King's Indian Defense"]),
  lineFromMoves(9, "kid", "Samisch 6...c5", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f3","O-O","Be3","c5","d5","e6","Qd2","exd5","cxd5","a6"], "Samisch c5 — queenside play.", ["King's Indian Defense"]),
  lineFromMoves(10, "kid", "London vs KID", ["d4","Nf6","Nf3","g6","c4","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5"], "London transposition — still ...e5.", ["King's Indian Defense"]),
  lineFromMoves(11, "kid", "5.Nf3 Fianchetto", ["d4","Nf6","c4","g6","Nf3","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5","e4","c6"], "Fianchetto with ...c6 support.", ["King's Indian Defense"]),
  lineFromMoves(12, "kid", "Benoni-style ...c5", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","Qd2","Nf6"], "Sometimes ...c5 is the right break instead of ...e5.", ["King's Indian Defense"]),
  lineFromMoves(13, "kid", "Classical 9...f5", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","g4","fxg4"], "Classical f5 — main break.", ["King's Indian Defense"]),
  lineFromMoves(14, "kid", "Four Pawns 8.Be2", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f4","O-O","Nf3","c5","d5","e6","Be2","exd5","cxd5","Re8"], "Four Pawns Be2 — ...Re8.", ["King's Indian Defense"]),
  lineFromMoves(15, "kid", "6.Be2 Classical", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7"], "Be2 classical tabiya.", ["King's Indian Defense"]),
  lineFromMoves(16, "kid", "Smyslov 7.O-O", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","a5"], "Smyslov ...a5 — queenside space.", ["King's Indian Defense"]),
  lineFromMoves(17, "kid", "Mar del Plata — ...f5", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","Qd2","Nf6","g4","Nh5"], "The Mar del Plata ...f5 break leads to sharp play.", ["King's Indian Defense","Mar del Plata"]),
  lineFromMoves(18, "kid", "Sämisch 7...Nbd7", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f3","O-O","Be3","e5","d5","c5","Qd2","a6"], "Samisch ...e5 and ...c5.", ["King's Indian Defense"]),
  lineFromMoves(19, "kid", "9...Nd7 Classical", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5"], "Nd7 reroute — prep f5.", ["King's Indian Defense"]),
  lineFromMoves(20, "kid", "5.g3 Fianchetto", ["d4","Nf6","c4","g6","Nf3","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5","e4","c6"], "White fianchettos — still ...e5.", ["King's Indian Defense"]),
  lineFromMoves(21, "kid", "Averbakh 8.d5", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7"], "Full Averbakh tabiya.", ["King's Indian Defense"]),
  lineFromMoves(22, "kid", "Exchange 7.Nxd4", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","h3","Nf6","g4","Nh5"], "Exchange on d4 — ...f5 anyway.", ["King's Indian Defense"]),
  mkLine(
    23,
    "kid_panno",
    "Panno — ...b6 and ...Ba6",
    "Line #23 · Panno variation",
    "The Panno waits with ...b6 and ...Ba6 before committing.",
    ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Re1","b6","Bf1","Ba6"],
    [
      "d4.",
      "...Nf6.",
      "c4.",
      "...g6.",
      "Nc3.",
      "...Bg7.",
      "e4.",
      "...d6.",
      "Nf3.",
      "...O-O.",
      "Be2.",
      "...e5.",
      "O-O.",
      "...Nc6.",
      "d5.",
      "...Ne7.",
      "Re1.",
      "...b6 — Panno!",
      "Bf1.",
      "...Ba6 — trade light bishop.",
    ],
    ["King's Indian Defense","Panno"]
  ),
  lineFromMoves(24, "kid", "Samisch 8.Qd2", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f3","O-O","Be3","c5","d5","e6","Qd2","exd5","cxd5","a6"], "Samisch Qd2 — ...a6.", ["King's Indian Defense"]),
  lineFromMoves(25, "kid", "Classical 10.f3", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5"], "f3 prep — then ...f5.", ["King's Indian Defense"]),
  lineFromMoves(26, "kid", "6.h3 Anti-g4", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","Qd2","Nf6","g4","fxg4"], "h3 anti-g4 — ...f5 anyway.", ["King's Indian Defense"]),
  lineFromMoves(27, "kid", "Old Main 7...Na6", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","g4","Nf6","h3","Nh5"], "Old main ...Na6 reroute.", ["King's Indian Defense"]),
  mkLine(
    28,
    "kid_glfeld",
    "Gligoric — ...Ne7-f5",
    "Line #28 · Gligoric system",
    "Gligoric's ...Ne7 and ...f5 is a KID classic.",
    ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","g4","Nf6"],
    [
      "d4.",
      "...Nf6.",
      "c4.",
      "...g6.",
      "Nc3.",
      "...Bg7.",
      "e4.",
      "...d6.",
      "Nf3.",
      "...O-O.",
      "Be2.",
      "...e5.",
      "O-O.",
      "...Nc6.",
      "d5.",
      "...Ne7.",
      "Ne1.",
      "...Nd7.",
      "f3.",
      "...f5!",
      "g4.",
      "...Nf6 — knight hops back.",
    ],
    ["King's Indian Defense","Gligoric"]
  ),
  lineFromMoves(29, "kid", "5.Be2 Setup", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","a5"], "Be2 with ...a5 — queenside space.", ["King's Indian Defense"]),
  lineFromMoves(30, "kid", "Four Pawns 9.exf5", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f4","O-O","Nf3","c5","d5","e6","Be2","exd5","cxd5","Bg4"], "Four Pawns ...Bg4 pin.", ["King's Indian Defense"]),
  lineFromMoves(31, "kid", "7.a4 Bayonet", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","g4","Nf6"], "Bayonet a4 — ...f5 response.", ["King's Indian Defense"]),
  lineFromMoves(32, "kid", "6...c5 Benoni", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","c5","d5","e6","O-O","exd5","cxd5","Bg4"], "Benoni c5 with ...Bg4.", ["King's Indian Defense"]),
  lineFromMoves(33, "kid", "Petrosian 9...f5", ["d4","Nf6","c4","g6","Nf3","Bg7","g3","O-O","Bg2","d6","O-O","Nbd7","Nc3","e5","e4","c6","Re1","Re8","h3","exd4","Nxd4","Nc5"], "Petrosian f5 Bxf5.", ["King's Indian Defense"]),
  lineFromMoves(34, "kid", "Classical 11.g4", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","h3","Nf6"], "Mar del Plata g4 — complex kingside.", ["King's Indian Defense"]),
  lineFromMoves(35, "kid", "Fortress Classical", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","Qd2","Nf6"], "Full classical fortress — know the tabiya.", ["King's Indian Defense"]),
];
