import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything.";

/** Potluck course — generated from validated templates. */
export default [
  lineFromMoves(1, "modern-full", "FULL Modern Defense — Line 1", ["e4","g6","d4","Bg7","Nc3","d6","f4","c6","Nf3","Bg4","Be3","Nd7","h3","Bxf3","Qxf3","e5","dxe5","dxe5"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 1.", ["FULL Modern Defense"]),
  lineFromMoves(2, "modern-full", "FULL Modern Defense — Line 2", ["e4","g6","d4","Bg7","Nc3","d6","Be3","a6","Qd2","b5","f3","Bb7","O-O-O","Nd7","g4","c5"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 2.", ["FULL Modern Defense"]),
  lineFromMoves(3, "modern-full", "FULL Modern Defense — Line 3", ["e4","g6","d4","Bg7","Nf3","d6","g3","Nf6","Bg2","O-O","O-O","Nbd7","c3","e5","Nbd2","Re8"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 3.", ["FULL Modern Defense"]),
  lineFromMoves(4, "modern-full", "FULL Modern Defense — Line 4", ["e4","g6","d4","Bg7","Nc3","d6","Be3","Nf6","Qd2","O-O","Bh6","c5","Bxg7","Kxg7","f3","Nc6","Nge2","e5"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 4.", ["FULL Modern Defense"]),
  lineFromMoves(5, "modern-full", "FULL Modern Defense — Line 5", ["e4","g6","d4","Bg7","Nc3","d6","f4","c6","Nf3","Bg4","Be3","Nd7","h3","Bxf3","Qxf3","e5"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 5.", ["FULL Modern Defense"]),
  lineFromMoves(6, "modern-full", "FULL Modern Defense — Line 6", ["e4","g6","d4","Bg7","Nf3","d6","c3","Nf6","Be2","O-O","O-O","Nbd7","Re1","e5","Nbd2","Re8"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 6.", ["FULL Modern Defense"]),
  lineFromMoves(7, "modern-full", "FULL Modern Defense — Line 7", ["e4","g6","c4","Bg7","d4","d6","Nc3","Nf6","f3","O-O","Be3","e5","d5","c5","Qd2","a5"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 7.", ["FULL Modern Defense"]),
  lineFromMoves(8, "modern-full", "FULL Modern Defense — Line 8", ["e4","g6","d4","Bg7","Nc3","d6","Be3","Nf6","Qd2","O-O","O-O-O","c5","f3","Nc6","dxc5","dxc5"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 8.", ["FULL Modern Defense"]),
  lineFromMoves(9, "modern-full", "FULL Modern Defense — Line 9", ["e4","g6","d4","Bg7","Nc3","d6","Be3","Nf6","f3","O-O","Qd2","c5","dxc5","dxc5","O-O-O","Nc6"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 9.", ["FULL Modern Defense"]),
  lineFromMoves(10, "modern-full", "FULL Modern Defense — Line 10", ["e4","g6","d4","Bg7","Nge2","d6","Ng3","Nf6","Be2","O-O","O-O","c5","c3","Nc6","f4","e5"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 10.", ["FULL Modern Defense"]),
  lineFromMoves(11, "modern-full", "FULL Modern Defense — Line 11", ["e4","d6","d4","Nf6","Nc3","g6","Nf3","Bg7","Be2","O-O","O-O","Nbd7","Re1","e5","Bf1","Re8","g3","c5","Bg2","cxd4","Nxd4","Nc5"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 11.", ["FULL Modern Defense"]),
  lineFromMoves(12, "modern-full", "FULL Modern Defense — Line 12", ["e4","d6","Nc3","Nf6","d4","g6","Be3","Bg7","Qd2","O-O","O-O-O","c5","f3","Nc6","Nge2","b5","Bh6","Bxh6","Qxh6","e5","dxe5","dxe5","Qe3","Bf5","g4","Bxg4","fxg4","Nxg4","Qf3","Nf6","h3","Nh5","Qd3","Qe7","Nd5","Qd7"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 12.", ["FULL Modern Defense"]),
  lineFromMoves(13, "modern-full", "FULL Modern Defense — Line 13", ["e4","d6","d4","Nf6","Nc3","g6","Nf3","Bg7","Be2","O-O","O-O","Nbd7","Re1","e5","Bf1","Re8","g3","c5"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 13.", ["FULL Modern Defense"]),
  lineFromMoves(14, "modern-full", "FULL Modern Defense — Line 14", ["e4","d6","d4","Nf6","Nc3","g6","Nf3","Bg7","Be2","O-O","O-O","Nbd7","Re1","e5","Bf1","Re8","g3","c5","Bg2","cxd4"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 14.", ["FULL Modern Defense"]),
  lineFromMoves(15, "modern-full", "FULL Modern Defense — Line 15", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 15.", ["FULL Modern Defense"]),
  lineFromMoves(16, "modern-full", "FULL Modern Defense — Line 16", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","g4","Nf6"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 16.", ["FULL Modern Defense"]),
  lineFromMoves(17, "modern-full", "FULL Modern Defense — Line 17", ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5","O-O","Nc6","d5","Ne7","Ne1","Nd7","f3","f5","g4","Nf6","h3","Nh5"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Line 17.", ["FULL Modern Defense"]),
  lineFromMoves(18, "modern-full", "FULL Modern Defense — Variation 18", ["e4","g6","d4","Bg7","Nc3","d6","f4","c6","Nf3","Bg4","Be3","Nd7","h3","Bxf3","Qxf3","e5","dxe5","dxe5"], "EVERY variation from the Modern — 1...g6 and ...Bg7 against anything. Alternate line 18.", ["FULL Modern Defense"]),
];
