import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack.";

/** Potluck course — P1 community-demand batch. */
export default [
  lineFromMoves(1, "najdorf-starter", "Najdorf Starter — Line 1", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Be2","e5","Nb3","Be6","O-O","Be7"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 1.", ["Najdorf Starter"]),
  lineFromMoves(2, "najdorf-starter", "Najdorf Starter — Line 2", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Bg5","e6","f4","Be7","Qf3","Qc7"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 2.", ["Najdorf Starter"]),
  lineFromMoves(3, "najdorf-starter", "Najdorf Starter — Line 3", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Be3","e5","Nb3","Be6","f3","Be7"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 3.", ["Najdorf Starter"]),
  lineFromMoves(4, "najdorf-starter", "Najdorf Starter — Line 4", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","g3","e5","Nde2","Be6","Bg2","Be7"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 4.", ["Najdorf Starter"]),
  lineFromMoves(5, "najdorf-starter", "Najdorf Starter — Line 5", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","Nc6","Be3","e6","Qd2","a6","O-O-O","Bd7","f4","b5"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 5.", ["Najdorf Starter"]),
  lineFromMoves(6, "najdorf-starter", "Najdorf Starter — Line 6", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","g6","Be3","Bg7","f3","O-O","Qd2","Nc6","O-O-O","Bd7","g4","Rc8"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 6.", ["Najdorf Starter"]),
  lineFromMoves(7, "najdorf-starter", "Najdorf Starter — Line 7", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Be3","e5","Nb3","Be6","f3","Be7","Qd2","O-O","O-O-O","b5"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 7.", ["Najdorf Starter"]),
  lineFromMoves(8, "najdorf-starter", "Najdorf Starter — Line 8", ["e4","c5","c3","d5","exd5","Qxd5","d4","Nf6","Nf3","e6","Be2","Nc6","O-O","Be7","Re1","O-O"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 8.", ["Najdorf Starter"]),
  lineFromMoves(9, "najdorf-starter", "Najdorf Starter — Line 9", ["e4","c5","c3","Nf6","e5","Nd5","d4","cxd4","cxd4","e6","Nf3","d6","Bc4","Nb6","Bb3","N8d7"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 9.", ["Najdorf Starter"]),
  lineFromMoves(10, "najdorf-starter", "Najdorf Starter — Line 10", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","e6","Be3","a6","f3","b5","Qd2","Bb7","O-O-O","Nbd7","g4","b4"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 10.", ["Najdorf Starter"]),
  lineFromMoves(11, "najdorf-starter", "Najdorf Starter — Line 11", ["e4","c5","Nc3","Nc6","f4","g6","Nf3","Bg7","Bb5","Nd4","Bxd7+","Qxd7","O-O","e6","d3","Nge7"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 11.", ["Najdorf Starter"]),
  lineFromMoves(12, "najdorf-starter", "Najdorf Starter — Line 12", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","Nc6","Ndb5","Bd7","Nxd6+","exd6","Nd5","Be7"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 12.", ["Najdorf Starter"]),
  lineFromMoves(13, "najdorf-starter", "Najdorf Starter — Line 13", ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","g6","Nc3","Bg7","Be3","Nf6","f3","O-O","Qd2","d6","O-O-O","Bd7","g4","Rc8"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 13.", ["Najdorf Starter"]),
  lineFromMoves(14, "najdorf-starter", "Najdorf Starter — Line 14", ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","e6","Nc3","Qc7","Be2","a6","O-O","Nf6","Be3","Bb4"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 14.", ["Najdorf Starter"]),
  lineFromMoves(15, "najdorf-starter", "Najdorf Starter — Line 15", ["e4","c5","Nf3","e6","d4","cxd4","Nxd4","a6","Nc3","Qc7","Be2","Nf6","O-O","Bb4","Qd3","O-O"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 15.", ["Najdorf Starter"]),
  lineFromMoves(16, "najdorf-starter", "Najdorf Starter — Line 16", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Bb5+","Bd7","Bxd7+","Qxd7","Nc3","g6","O-O","Nc6","Ndb5","O-O-O"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 16.", ["Najdorf Starter"]),
  lineFromMoves(17, "najdorf-starter", "Najdorf Starter — Line 17", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","g6","Ndb5","Nbd7","Nxd6+","exd6","Nd5","Bg7","Ne7","Nf8","Nxc8","Ne6"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 17.", ["Najdorf Starter"]),
  lineFromMoves(18, "najdorf-starter", "Najdorf Starter — Line 18", ["e4","c5","f4","d6","Nf3","Nf6","Nc3","g6","Bb5+","Bd7","Bxd7+","Qxd7","O-O","Bg7","d3","O-O"], "Core Najdorf ...a6 against 6.Be2, 6.Bg5, and English setups — a solid starter pack. Line 18.", ["Najdorf Starter"]),
];
