import { mkLine, lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION =
  "The Petrov Defense: 1.e4 e5 2.Nf3 Nf6 — twenty-four solid lines where Black mirrors White's knight and fights for equality with ...Nxe4.";

export default [
  mkLine(
    1,
    "petrov_main",
    "Classical Petrov — ...Nxe4",
    "Line #1 · Main tabiya",
    "The Petrov is the ultimate equalizer. Learn the ...Nxe4 sequence cold.",
    ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","d4","d5","Bd3","Bd6","O-O","O-O","c4","c6","cxd5","cxd5"],
    [
      "e4.",
      "...e5 — mirror the center.",
      "Nf3.",
      "...Nf6 — Petrov!",
      "Nxe5.",
      "...d6 — kick the knight.",
      "Nf3.",
      "...Nxe4 — take the pawn.",
      "d4.",
      "...d5 — strike back.",
      "Bd3.",
      "...Bd6 — develop.",
      "O-O.",
      "...O-O.",
      "c4.",
      "...c6 — support d5.",
      "cxd5.",
      "...cxd5 — solid structure.",
    ],
    ["Petrov Defense","Classical"]
  ),
  mkLine(
    2,
    "petrov_steinitz",
    "Steinitz Attack — ...Nc6",
    "Line #2 · ...Nc6 development",
    "Against the Steinitz Attack, ...Nc6 and ...Be7 keep things solid.",
    ["e4","e5","Nf3","Nf6","Nc3","Nc6","Bb5","Bb4","O-O","O-O","d3","d6","Bg5","Bxc3","bxc3","Qe7"],
    [
      "e4.",
      "...e5.",
      "Nf3.",
      "...Nf6.",
      "Nc3.",
      "...Nc6 — Steinitz tabiya.",
      "Bb5.",
      "...Bb4 pin.",
      "O-O.",
      "...O-O.",
      "d3.",
      "...d6.",
      "Bg5.",
      "...Bxc3 trade.",
      "bxc3.",
      "...Qe7 — connect rooks.",
    ],
    ["Petrov Defense","Steinitz"]
  ),
  lineFromMoves(3, "petrov", "3.Nxe5 d6 Classical", ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","d4","d5","Bd3","Be7","O-O","O-O","Re1","c6"], "Classical ...Be7 instead of ...Bd6.", ["Petrov Defense"]),
  lineFromMoves(4, "petrov", "4.d4 d5 Center", ["e4","e5","Nf3","Nf6","d4","Nxe4","Bd3","d5","Nxe5","Bd6","O-O","O-O","Re1","Re8"], "Modern 3.d4 line — same ...Nxe4 and ...d5.", ["Petrov Defense"]),
  mkLine(
    5,
    "petrov_bxf7",
    "Bxf7+ Sideline",
    "Line #5 · Survive Bxf7+",
    "White tries Bxf7+ tricks — know the refutation.",
    ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","d4","d5","Bd3","Bd6","O-O","O-O","Re1","Re8","c4","c6","cxd5","cxd5","Nc3","Nxc3"],
    [
      "e4.",
      "...e5.",
      "Nf3.",
      "...Nf6.",
      "Nxe5.",
      "...d6.",
      "Nf3.",
      "...Nxe4.",
      "d4.",
      "...d5.",
      "Bd3.",
      "...Bd6.",
      "O-O.",
      "...O-O.",
      "Re1.",
      "...Re8.",
      "c4.",
      "...c6.",
      "cxd5.",
      "...cxd5.",
      "Nc3.",
      "...Nxc3 — simplify.",
    ],
    ["Petrov Defense"]
  ),
  lineFromMoves(6, "petrov", "5.c4 IQP", ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","d4","d5","Bd3","Bd6","O-O","O-O","c4","c6","Nc3","Nxc3"], "IQP structures after ...Nxc3.", ["Petrov Defense"]),
  lineFromMoves(7, "petrov", "3.d3 Slow", ["e4","e5","Nf3","Nf6","d3","Nc6","Be2","Bc5","O-O","d6","c3","O-O","Nbd2","a5"], "Slow d3 — develop with ...Nc6 and ...Bc5.", ["Petrov Defense"]),
  mkLine(
    8,
    "petrov_three_knights",
    "Three Knights — ...Nc6",
    "Line #8 · Three Knights setup",
    "When White avoids Nxe5, ...Nc6 is flexible.",
    ["e4","e5","Nf3","Nf6","Nc3","Nc6","Bb5","Bb4","O-O","O-O","d3","d6","Bg5","Bxc3","bxc3","h6","Bh4","g5"],
    [
      "e4.",
      "...e5.",
      "Nf3.",
      "...Nf6.",
      "Nc3.",
      "...Nc6.",
      "Bb5.",
      "...Bb4.",
      "O-O.",
      "...O-O.",
      "d3.",
      "...d6.",
      "Bg5.",
      "...Bxc3.",
      "bxc3.",
      "...h6.",
      "Bh4.",
      "...g5 — kick the bishop.",
    ],
    ["Petrov Defense"]
  ),
  lineFromMoves(9, "petrov", "6.h3 Anti-Bg4", ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","d4","d5","Bd3","Bd6","O-O","O-O","c4","c6","Re1","Re8"], "Anti-Bg4 h3 line — solid ...Re8.", ["Petrov Defense"]),
  lineFromMoves(10, "petrov", "4.Nc3 Modern", ["e4","e5","Nf3","Nf6","Nc3","Nc6","Bb5","Nd4","Ba4","Bc5","O-O","O-O","Nxe5","Qe7"], "Modern 4...Nd4 — central knight.", ["Petrov Defense"]),
  lineFromMoves(11, "petrov", "5.Qe2 Sideline", ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","Qe2","Qe7","d3","Nf6","Bg5","Qxe2+","Bxe2","Be7"], "Qe2 sideline — trade queens for comfort.", ["Petrov Defense"]),
  lineFromMoves(12, "petrov", "Bxf7+ Trap", ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","d4","d5","Bd3","Bd6","O-O","O-O"], "Bxf7+ trick — king walks but survives.", ["Petrov Defense"]),
  lineFromMoves(13, "petrov", "Cochrane Gambit — Survive", ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","d4","d5","Bd3","Bd6","O-O","O-O","Bc4","Nd7","Bb5","Ndf6"], "White plays the crazy Cochrane? Hang on and counterattack.", ["Petrov Defense","Cochrane"]),
  lineFromMoves(14, "petrov", "7.Nbd2 Block", ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","d4","d5","Bd3","Bd6","O-O","O-O","Nbd2","Nf6"], "Nbd2 block — retreat knight to f6.", ["Petrov Defense"]),
  lineFromMoves(15, "petrov", "4.Bd3 Exchange", ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","Bd3","Nf6","O-O","Be7","Re1","O-O","c4","c6"], "Early Bd3 — same Petrov structure.", ["Petrov Defense"]),
  lineFromMoves(16, "petrov", "6.Re1 Pressure", ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","d4","d5","Bd3","Bd6","O-O","O-O","Re1","Re8","c4","c6"], "Re1 pressure — hold with ...Re8.", ["Petrov Defense"]),
  lineFromMoves(17, "petrov", "3.Bc4 Italian", ["e4","e5","Nf3","Nf6","Bc4","Nxe4","Bxf7+","Kxf7","Nxe5+","Ke8","Qf3","d6","Nc4","Nf6"], "Italian Bc4 — same Bxf7+ survival.", ["Petrov Defense"]),
  lineFromMoves(18, "petrov", "Knight d4 — Central", ["e4","e5","Nf3","Nf6","Nc3","Nc6","Bb5","Bb4","O-O","O-O","d3","d6","Ba6","Bd7","Bxb7","Bc8","Bxa8","Bd7"], "The ...Nd4 knight is a Petrov weapon in many lines.", ["Petrov Defense"]),
  lineFromMoves(19, "petrov", "5.c4 Aggressive", ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","d4","d5","Bd3","Bd6","O-O","O-O","c4","Bf5"], "Aggressive c4 — meet with ...Bf5.", ["Petrov Defense"]),
  lineFromMoves(20, "petrov", "8.a4 Space", ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","d4","d5","Bd3","Bd6","O-O","O-O","a4","a6"], "a4 space — prophylaxis with ...a6.", ["Petrov Defense"]),
  lineFromMoves(21, "petrov", "4.d3 Petrov Declined", ["e4","e5","Nf3","Nf6","d3","Nc6","Be2","Bc5","O-O","d6","c3","O-O","Nbd2","a5"], "Petrov declined — normal development.", ["Petrov Defense"]),
  lineFromMoves(22, "petrov", "7.Bg5 Pin", ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","d4","d5","Bd3","Bd6","O-O","O-O","Bg5","f6"], "Bg5 pin — kick with ...f6.", ["Petrov Defense"]),
  lineFromMoves(23, "petrov", "6.Nc3 Trade", ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4","d4","d5","Bd3","Bd6","O-O","O-O","Nc3","Nxc3","bxc3","Nd7"], "Nc3 trade line — doubled pawns for White.", ["Petrov Defense"]),
  lineFromMoves(24, "petrov", "5.Nc3 Co-Equal", ["e4","e5","Nf3","Nf6","Nc3","Nc6","Bb5","Bb4","O-O","O-O","d3","d6","Bg5","Bxc3","bxc3","Qe7"], "Repeat Steinitz structure — know it cold.", ["Petrov Defense"]),
];
