import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights.";

/** Potluck course — generated from validated templates. */
export default [
  lineFromMoves(1, "pressure-caro", "Pressure the Caro-Kann — Line 1", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5","Ng3","Bg6","Nf3","Nd7","h4","h6","Bd3","Bxd3","Qxd3","Qc7"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 1.", ["Pressure the Caro-Kann"]),
  lineFromMoves(2, "pressure-caro", "Pressure the Caro-Kann — Line 2", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","cxd4","cxd4","Rc8"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 2.", ["Pressure the Caro-Kann"]),
  lineFromMoves(3, "pressure-caro", "Pressure the Caro-Kann — Line 3", ["e4","c6","d4","d5","exd5","cxd5","Bd3","Nc6","c3","Nf6","Bf4","Bg4","Qb3","Qd7"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 3.", ["Pressure the Caro-Kann"]),
  lineFromMoves(4, "pressure-caro", "Pressure the Caro-Kann — Line 4", ["e4","c6","d4","d5","exd5","cxd5","c4","Nf6","Nc3","e6","Nf3","Be7","cxd5","Nxd5"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 4.", ["Pressure the Caro-Kann"]),
  lineFromMoves(5, "pressure-caro", "Pressure the Caro-Kann — Line 5", ["e4","c6","d4","d5","Nc3","g6","Nf3","Bg7","h3","e6","Bd3","Ne7","O-O","O-O","Re1","Nd7","Bf4","f6"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 5.", ["Pressure the Caro-Kann"]),
  lineFromMoves(6, "pressure-caro", "Pressure the Caro-Kann — Line 6", ["e4","c6","Nc3","d5","Nf3","Bg4","h3","Bxf3","Qxf3","e6","d4","Nf6","Bd3","Be7"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 6.", ["Pressure the Caro-Kann"]),
  lineFromMoves(7, "pressure-caro", "Pressure the Caro-Kann — Line 7", ["e4","c6","f3","d5","d4","e6","Nc3","dxe4","fxe4","f5","Nf3","fxe4","Nxe4","Nf6"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 7.", ["Pressure the Caro-Kann"]),
  lineFromMoves(8, "pressure-caro", "Pressure the Caro-Kann — Line 8", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","O-O-O","Nb5","Re8"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 8.", ["Pressure the Caro-Kann"]),
  lineFromMoves(9, "pressure-caro", "Pressure the Caro-Kann — Line 9", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Nd7","Ng5","Ngf6","Bd3","e6","N1f3","Be7","O-O","O-O"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 9.", ["Pressure the Caro-Kann"]),
  lineFromMoves(10, "pressure-caro", "Pressure the Caro-Kann — Line 10", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","cxd4"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 10.", ["Pressure the Caro-Kann"]),
  lineFromMoves(11, "pressure-caro", "Pressure the Caro-Kann — Line 11", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5","Nd6+","Qxd6","Bd2","Nd7","Bc3","O-O-O"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 11.", ["Pressure the Caro-Kann"]),
  lineFromMoves(12, "pressure-caro", "Pressure the Caro-Kann — Line 12", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Nd7","Nf3","Ngf6","Nxf6+","Nxf6","Bd3","e6","O-O","Bd6","Re1","O-O","c4","Re8"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 12.", ["Pressure the Caro-Kann"]),
  lineFromMoves(13, "pressure-caro", "Pressure the Caro-Kann — Line 13", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nd7","Ng5","Be7","Nxe6","Nh6"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 13.", ["Pressure the Caro-Kann"]),
  lineFromMoves(14, "pressure-caro", "Pressure the Caro-Kann — Line 14", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","a6"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 14.", ["Pressure the Caro-Kann"]),
  lineFromMoves(15, "pressure-caro", "Pressure the Caro-Kann — Line 15", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Nf6","Nxf6+","gxf6","c3","Bg7","Bd3","e5","Qh5","Qe7","Nf3","f5"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 15.", ["Pressure the Caro-Kann"]),
  lineFromMoves(16, "pressure-caro", "Pressure the Caro-Kann — Line 16", ["e4","c6","d4","d5","e5","Bf5","Nf3","e6","Be2","c5","O-O","Nc6","c3","Qb6","Na3","O-O-O"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 16.", ["Pressure the Caro-Kann"]),
  lineFromMoves(17, "pressure-caro", "Pressure the Caro-Kann — Line 17", ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5","Bc4","e6","Ng5","Bg6","N1f3","h6","Nh4","Nd7"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 17.", ["Pressure the Caro-Kann"]),
  lineFromMoves(18, "pressure-caro", "Pressure the Caro-Kann — Line 18", ["e4","c6","d4","d5","exd5","cxd5","c4","Nf6","Nc3","e6","Nf3","Be7","cxd5","Nxd5","Bd3","Nc6"], "White weapons vs the Caro-Kann — Advance, Exchange, and Two Knights. Line 18.", ["Pressure the Caro-Kann"]),
];
