import { mkLine, lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION =
  "The Rousseau Gambit: 1.e4 e5 2.Nf3 Nc6 3.Bc4 f5 — twenty-four aggressive lines where Black sacrifices a pawn for rapid kingside attack.";

export default [
  mkLine(
    1,
    "rousseau_main",
    "Main Line — ...f5 Gambit",
    "Line #1 · Core gambit",
    "White plays the Italian? Hit them with ...f5 and open the f-file.",
    ["e4","e5","Nf3","Nc6","Bc4","f5","d3","fxe4","dxe4","Nf6","Ng5","d5","exd5","Na5","Bb5+","c6","dxc6","bxc6"],
    [
      "e4.",
      "...e5 — classical.",
      "Nf3.",
      "...Nc6.",
      "Bc4.",
      "...f5! — Rousseau time!",
      "d3 — safe choice.",
      "...fxe4 — take in the center.",
      "dxe4.",
      "...Nf6 — develop with tempo.",
      "Ng5.",
      "...d5! — blast open.",
      "exd5.",
      "...Na5 — knight hunt the bishop.",
      "Bb5+.",
      "...c6 — force trades.",
      "dxc6.",
      "...bxc6 — open b-file.",
    ],
    ["Rousseau Gambit","Main Line"]
  ),
  lineFromMoves(2, "rousseau", "Accept with exf5", ["e4","e5","Nf3","Nc6","Bc4","f5","d3","fxe4","dxe4","Nf6","O-O","Be7","Bb5","O-O","Ba6","Bd6","Bxb7","Bxb7"], "If White grabs f5, ...e4 and ...d5 give you a monster center.", ["Rousseau Gambit"]),
  lineFromMoves(3, "rousseau", "4.Bxg8 Decline", ["e4","e5","Nf3","Nc6","Bc4","f5","d4","fxe4","Nxe5","Nxe5","dxe5","d5","O-O","Bd7"], "If White takes on g8, develop with ...Nf6 and ...Be6.", ["Rousseau Gambit"]),
  lineFromMoves(4, "rousseau", "5.Nc3 Development", ["e4","e5","Nf3","Nc6","Bc4","f5","Nc3","Nf6","d3","fxe4","dxe4","Bc5","O-O","d6","Bg5","Be6"], "Nc3 from White — play ...Nf6 and fianchetto ideas.", ["Rousseau Gambit"]),
  lineFromMoves(5, "rousseau", "Knight a5 — Bishop Hunt", ["e4","e5","Nf3","Nc6","Bc4","f5","Nc3","Nf6","d3","Bc5","O-O","Ne7","Bb5","O-O","Ba6","Ng6","Bxb7","Bxb7","Nd5","Bc8"], "The ...Na5 chase on the c4 bishop is a Rousseau classic.", ["Rousseau Gambit"]),
  lineFromMoves(6, "rousseau", "4.d4 Central", ["e4","e5","Nf3","Nc6","Bc4","f5","d4","fxe4","Nxe5","Nxe5","dxe5","d5","Bb3","Nf6","O-O","Be7"], "White plays d4 — take and meet ...d5.", ["Rousseau Gambit"]),
  lineFromMoves(7, "rousseau", "6.O-O Castle", ["e4","e5","Nf3","Nc6","Bc4","f5","d3","fxe4","dxe4","Nf6","O-O","Bc5","Nc3","d6","Bg5","Be6"], "Quiet castling line — develop with ...Bc5.", ["Rousseau Gambit"]),
  lineFromMoves(8, "rousseau", "Queen h4 — Attack", ["e4","e5","Nf3","Nc6","Bc4","f5","exf5","e4","Ng5","d5","Bb5","Nf6","O-O","Bd7","Ba6","Be7","Bxb7","O-O","Bxa8","Bc8"], "Bring the queen to h4 when White gets sloppy.", ["Rousseau Gambit","Tactics"]),
  lineFromMoves(9, "rousseau", "5.Bb5+ Check", ["e4","e5","Nf3","Nc6","Bc4","f5","d3","fxe4","dxe4","Nf6","Ng5","d5","exd5","Na5","Bb5+","c6","Qe2","Be7"], "After Bb5+, ...c6 and ...Be7.", ["Rousseau Gambit"]),
  lineFromMoves(10, "rousseau", "3.Bb5 Pin", ["e4","e5","Nf3","Nc6","Bb5","f5","Nc3","fxe4","Nxe4","Nf6","Nxf6+","Qxf6","O-O","d6","Re1","Be7"], "If White pins with Bb5, still play ...f5!", ["Rousseau Gambit"]),
  lineFromMoves(11, "rousseau", "4.c3 Slow", ["e4","e5","Nf3","Nc6","Bc4","f5","c3","Nf6","d3","fxe4","dxe4","Bc5","O-O","d6","Be3","Be6"], "Slow c3 — fianchetto with ...Bc5.", ["Rousseau Gambit"]),
  lineFromMoves(12, "rousseau", "7.f4 Push", ["e4","e5","Nf3","Nc6","Bc4","f5","Be2","fxe4","O-O","Be7","Nd4","Nh6","Nxc6","O-O","Nxd8","Bxd8","Bd3","Be7"], "When bishop retreats to c4, ...Nxc4 and ...Nf6.", ["Rousseau Gambit"]),
  lineFromMoves(13, "rousseau", "Bishop c5 — Development", ["e4","e5","Nf3","Nc6","Bc4","f5","c3","Nf6","d3","fxe4","dxe4","Bc5","O-O","Ne7","Bb5","O-O","Ba6","Ng6","Bxb7","Bxb7"], "Get the bishop to c5 and pressure f2.", ["Rousseau Gambit"]),
  lineFromMoves(14, "rousseau", "6.Bg5 Pin", ["e4","e5","Nf3","Nc6","Bc4","f5","d3","fxe4","dxe4","Nf6","O-O","Be7","Bb5","O-O","Ba6","Bd6"], "Meet Bg5 with ...Bc5 and castle.", ["Rousseau Gambit"]),
  lineFromMoves(15, "rousseau", "5.Qe2 Block", ["e4","e5","Nf3","Nc6","Bc4","f5","d4","fxe4","Nxe5","Nxe5","dxe5","d5","O-O","Bd7","Bb5","Be7"], "Qe2 block — develop with ...Nf6 and ...Bc5.", ["Rousseau Gambit"]),
  lineFromMoves(16, "rousseau", "4.Nc3 Early", ["e4","e5","Nf3","Nc6","Bc4","f5","Nc3","Nf6","d3","Bc5","O-O","Ne7","Bb5","O-O","Ba6","Ng6"], "Nc3 early — castle and play ...Bc5.", ["Rousseau Gambit"]),
  lineFromMoves(17, "rousseau", "8.Re1 Central", ["e4","e5","Nf3","Nc6","Bc4","f5","d3","fxe4","dxe4","Nf6","Ng5","d5","exd5","Na5","Bb3","Nxb3","axb3","e4"], "Re1 from White — keep the ...e4 pawn push.", ["Rousseau Gambit"]),
  lineFromMoves(18, "rousseau", "King Walk Kxf7", ["e4","e5","Nf3","Nc6","Bc4","f5","exf5","e4","Ng5","d5","Bb5","Nf6","O-O","Bd7","Ba6","Be7","Bxb7","O-O","Bxa8","Bc8"], "Sometimes the king walks to f7 — scary but practical in Rousseau.", ["Rousseau Gambit"]),
  lineFromMoves(19, "rousseau", "6.h4 Aggression", ["e4","e5","Nf3","Nc6","Bc4","f5","d3","fxe4","dxe4","Nf6","Ng5","d5","exd5","Na5","Bb5+","c6","Qe2","Be7"], "h4 aggression — solid development with ...Be7.", ["Rousseau Gambit"]),
  lineFromMoves(20, "rousseau", "3.d4 Scotch", ["e4","e5","Nf3","Nc6","Bc4","f5","Be2","fxe4","O-O","Be7","Nd4","Nh6","Nxc6","O-O","Nxd8","Bxd8"], "If White plays Scotch d4, still hit ...f5!", ["Rousseau Gambit"]),
  lineFromMoves(21, "rousseau", "7.Nd2 Block", ["e4","e5","Nf3","Nc6","Bc4","f5","d3","fxe4","dxe4","Nf6","Ng5","d5","exd5","Na5","Nd2","Nxc4","Nxc4","e4"], "Nd2 block — take on c4 and push ...e4.", ["Rousseau Gambit"]),
  lineFromMoves(22, "rousseau", "5.Be2 Solid", ["e4","e5","Nf3","Nc6","Bc4","f5","c3","Nf6","d3","fxe4","dxe4","Bc5","O-O","Ne7","Bb5","O-O"], "Be2 solid — trade knights and play ...Bc5.", ["Rousseau Gambit"]),
  lineFromMoves(23, "rousseau", "4.b4 Wing", ["e4","e5","Nf3","Nc6","Bc4","f5","d3","fxe4","dxe4","Nf6","O-O","Be7","Bb5","O-O","Ba6","Bd6"], "b4 wing push — same ...Na5 pattern.", ["Rousseau Gambit"]),
  lineFromMoves(24, "rousseau", "Decline 4.Bd3", ["e4","e5","Nf3","Nc6","Bc4","f5","Bd3","fxe4","Bxe4","Nf6","Bxc6","dxc6","O-O","Bc5","c3","O-O"], "Bd3 decline — take back and develop.", ["Rousseau Gambit"]),
];
