import { mkLine, lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION =
  "The Scandinavian Defense: 1.e4 d5 — twenty-five lines where Black immediately challenges White's e-pawn and fights for the center.";

export default [
  mkLine(
    1,
    "scandi_main",
    "Main Line — ...Qxd5",
    "Line #1 · Classical Scandinavian",
    "The Scandinavian is bold and simple: ...d5 and ...Qxd5, then develop fast.",
    ["e4","d5","exd5","Qxd5","Nc3","Qa5","d4","Nf6","Nf3","Bg4","Be2","Nc6","O-O","O-O-O","Be3","Kb8"],
    [
      "e4.",
      "...d5! — Scandinavian!",
      "exd5.",
      "...Qxd5 — queen recaptures.",
      "Nc3.",
      "...Qa5 — best retreat.",
      "d4.",
      "...Nf6 — develop.",
      "Nf3.",
      "...Bg4 pins!",
      "Be2.",
      "...Nc6.",
      "O-O.",
      "...O-O-O — long castle.",
      "Be3.",
      "...Kb8 — king safe.",
    ],
    ["Scandinavian Defense","Main Line"]
  ),
  mkLine(
    2,
    "scandi_nf6",
    "Modern — ...Nf6",
    "Line #2 · ...Nf6 without queen",
    "The modern ...Nf6 keeps the queen off the board.",
    ["e4","d5","exd5","Nf6","d4","Nxd5","Nf3","Bg4","Be2","Nc6","O-O","e6","c4","Nb6","Nc3","Be7"],
    [
      "e4.",
      "...d5!",
      "exd5.",
      "...Nf6 — modern!",
      "d4.",
      "...Nxd5 recaptures.",
      "Nf3.",
      "...Bg4 pin.",
      "Be2.",
      "...Nc6.",
      "O-O.",
      "...e6 — solid.",
      "c4.",
      "...Nb6 — reroute.",
      "Nc3.",
      "...Be7.",
    ],
    ["Scandinavian Defense","Modern"]
  ),
  lineFromMoves(3, "scandinavian", "3...Qd6 Sideline", ["e4","d5","exd5","Qxd5","Nc3","Qd6","d4","Nf6","Nf3","a6","Be2","Bg4","O-O","Nc6"], "Qd6 sideline — still playable.", ["Scandinavian Defense"]),
  lineFromMoves(4, "scandinavian", "4.Bb5+ Check", ["e4","d5","exd5","Qxd5","Nc3","Qa5","Bb5+","c6","d4","Nf6","Nf3","Bg4","Be2","e6"], "Bb5+ check — block with ...c6.", ["Scandinavian Defense"]),
  mkLine(
    5,
    "scandi_qd8",
    "Queen d8 — Solid",
    "Line #5 · ...Qd8 retreat",
    "When in doubt, ...Qd8 is the safe Scandinavian retreat.",
    ["e4","d5","exd5","Qxd5","Nc3","Qd8","d4","Nf6","Nf3","g6","Be2","Bg7","O-O","O-O","Re1","c6"],
    [
      "e4.",
      "...d5!",
      "exd5.",
      "...Qxd5.",
      "Nc3.",
      "...Qd8 — solid retreat.",
      "d4.",
      "...Nf6.",
      "Nf3.",
      "...g6 — fianchetto.",
      "Be2.",
      "...Bg7.",
      "O-O.",
      "...O-O.",
      "Re1.",
      "...c6 — support.",
    ],
    ["Scandinavian Defense"]
  ),
  lineFromMoves(6, "scandinavian", "5.c4 Space", ["e4","d5","exd5","Qxd5","Nc3","Qa5","d4","Nf6","Nf3","Bg4","Be2","Nc6","O-O","O-O-O"], "c4 space grab — develop with ...Nf6.", ["Scandinavian Defense"]),
  lineFromMoves(7, "scandinavian", "3...Qd6 Exchange", ["e4","d5","exd5","Qxd5","Nc3","Qd6","d4","Nf6","Nf3","Nc6","Be2","Bg4","O-O","O-O-O"], "Qd6 with ...Nc6 — active development.", ["Scandinavian Defense"]),
  mkLine(
    8,
    "scandi_bg4",
    "Bishop g4 Pin",
    "Line #8 · ...Bg4 always",
    "The ...Bg4 pin is your best friend in the Scandinavian.",
    ["e4","d5","exd5","Qxd5","Nc3","Qa5","d4","Nf6","Nf3","Bg4","Be2","Nc6","h3","Bxf3","Bxf3","e6","Be3","Bb4"],
    [
      "e4.",
      "...d5!",
      "exd5.",
      "...Qxd5.",
      "Nc3.",
      "...Qa5.",
      "d4.",
      "...Nf6.",
      "Nf3.",
      "...Bg4!",
      "Be2.",
      "...Nc6.",
      "h3.",
      "...Bxf3 trade.",
      "Bxf3.",
      "...e6.",
      "Be3.",
      "...Bb4 pin!",
    ],
    ["Scandinavian Defense"]
  ),
  lineFromMoves(9, "scandinavian", "6.Bg5 Pin", ["e4","d5","exd5","Qxd5","Nc3","Qa5","d4","Nf6","Nf3","Bg4","Bg5","e6","Be2","Nc6","O-O","O-O-O"], "Meet Bg5 with ...e6.", ["Scandinavian Defense"]),
  lineFromMoves(10, "scandinavian", "4.Nf3 Development", ["e4","d5","exd5","Qxd5","Nc3","Qa5","Nf3","Nf6","d4","Bg4","Be2","Nc6","O-O","O-O-O"], "Nf3 before d4 — same plan.", ["Scandinavian Defense"]),
  lineFromMoves(11, "scandinavian", "Modern 4.c4", ["e4","d5","exd5","Nf6","c4","c6","d4","cxd5","cxd5","Qxd5","Nc3","Qa5","Bd2","Bg4"], "Modern with c4 — queen comes out later.", ["Scandinavian Defense"]),
  lineFromMoves(12, "scandinavian", "5.Qd2 Block", ["e4","d5","exd5","Qxd5","Nc3","Qa5","d4","Nf6","Nf3","Bg4","Be2","Nc6","O-O","O-O-O"], "Qd2 block — develop normally.", ["Scandinavian Defense"]),
  mkLine(
    13,
    "scandi_long_castle",
    "Long Castle Attack",
    "Line #13 · ...O-O-O",
    "Castle long and push ...c5 or ...e5 for counterplay.",
    ["e4","d5","exd5","Qxd5","Nc3","Qa5","d4","Nf6","Nf3","Bg4","Be2","Nc6","O-O","O-O-O","h3","Bh5","a3","Kb8"],
    [
      "e4.",
      "...d5!",
      "exd5.",
      "...Qxd5.",
      "Nc3.",
      "...Qa5.",
      "d4.",
      "...Nf6.",
      "Nf3.",
      "...Bg4.",
      "Be2.",
      "...Nc6.",
      "O-O.",
      "...O-O-O!",
      "h3.",
      "...Bh5 — bishop stays.",
      "a3.",
      "...Kb8 — king safe.",
    ],
    ["Scandinavian Defense"]
  ),
  lineFromMoves(14, "scandinavian", "7.Nd2 Block", ["e4","d5","exd5","Qxd5","Nc3","Qa5","d4","Nf6","Nf3","Bg4","Be2","Nc6","O-O","O-O-O","Nd2","Kb8"], "Nd2 block — same structure.", ["Scandinavian Defense"]),
  lineFromMoves(15, "scandinavian", "3.Bb5+ Early", ["e4","d5","exd5","Nf6","d4","Nxd5","Nf3","Bg4","Be2","Nc6","O-O","Ne5","Nxe5","Nf6"], "Early Bb5+ — queen to e5.", ["Scandinavian Defense"]),
  lineFromMoves(16, "scandinavian", "4.g3 Fianchetto", ["e4","d5","exd5","Qxd5","Nc3","Qa5","g3","Nf6","Bg2","c6","Nf3","Bg4","O-O","Nbd7"], "g3 fianchetto — develop with ...Nf6.", ["Scandinavian Defense"]),
  lineFromMoves(17, "scandinavian", "6.c4 Central", ["e4","d5","exd5","Qxd5","Nc3","Qa5","d4","Nf6","Nf3","Bg4","Be2","Nc6","O-O","O-O-O"], "c4 central — same development.", ["Scandinavian Defense"]),
  lineFromMoves(18, "scandinavian", "Portuguese — ...Bg4 and ...Nd7", ["e4","d5","exd5","Qxd5","Nc3","Qd8","d4","Nf6","Nf3","g6","Nd5","Nbd7","Nxc7+","Qxc7","Ne5","Bg7"], "The Portuguese Scandinavian uses ...Bg4 and ...Nd7 for flexibility.", ["Scandinavian Defense","Portuguese"]),
  lineFromMoves(19, "scandinavian", "5.Bd2 Solid", ["e4","d5","exd5","Qxd5","Nc3","Qa5","d4","Nf6","Nf3","Bg4","Be2","Nc6","O-O","O-O-O"], "Bd2 solid — normal development.", ["Scandinavian Defense"]),
  lineFromMoves(20, "scandinavian", "8.a4 Pawn Storm", ["e4","d5","exd5","Qxd5","Nc3","Qa5","d4","Nf6","Nf3","Bg4","Be2","Nc6","O-O","O-O-O","a4","Kb8"], "a4 pawn storm — king to b8.", ["Scandinavian Defense"]),
  lineFromMoves(21, "scandinavian", "4.d3 Slow", ["e4","d5","exd5","Qxd5","Nc3","Qa5","d3","Nf6","Nf3","Bg4","Be2","Nc6","O-O","O-O-O"], "Slow d3 — same Scandinavian plan.", ["Scandinavian Defense"]),
  lineFromMoves(22, "scandinavian", "6.Be3 Develop", ["e4","d5","exd5","Qxd5","Nc3","Qa5","d4","Nf6","Nf3","Bg4","Be3","Nc6","Be2","O-O-O","O-O","Kb8"], "Be3 develop — mirror main line.", ["Scandinavian Defense"]),
  lineFromMoves(23, "scandinavian", "Modern 5.Bg5", ["e4","d5","exd5","Nf6","d4","Nxd5","Nf3","Bg4","Be2","Nc6","O-O","e6","Bg5","Be7","c4","Nb6"], "Bg5 in modern — ...Be7.", ["Scandinavian Defense"]),
  lineFromMoves(24, "scandinavian", "7.Re1 Central", ["e4","d5","exd5","Qxd5","Nc3","Qa5","d4","Nf6","Nf3","Bg4","Be2","Nc6","O-O","O-O-O","Re1","Kb8"], "Re1 central — hold the structure.", ["Scandinavian Defense"]),
  lineFromMoves(25, "scandinavian", "2.exd5 Only", ["e4","d5","exd5","Qxd5","Nc3","Qa5","d4","Nf6","Nf3","Bg4","Be2","Nc6","O-O","O-O-O","Be3","Kb8","a4","Re8"], "Full main line review — know every move.", ["Scandinavian Defense"]),
];
