import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "Scotch Game analysis with interesting sidelines and simple plans.";

/** Potluck course — generated from validated templates. */
export default [
  lineFromMoves(1, "scotch-white", "Scotch Game for White — Line 1", ["e4","e5","Nf3","Nc6","d4","Rb8","Nbd2","Nge7","c4","b5","c5","Rg8","a4","Nb4","Nb1","Bb7","Bd3","Rh8"], "Scotch Game analysis with interesting sidelines and simple plans. Line 1.", ["Scotch Game for White"]),
  lineFromMoves(2, "scotch-white", "Scotch Game for White — Line 2", ["e4","e5","Nf3","Nc6","d4","Qe7","Bd2","Qe6","Qe2","Qh6","d5","Nf6","dxc6","Qxd2+","Nfxd2","Kd8","Qf3","Bb4"], "Scotch Game analysis with interesting sidelines and simple plans. Line 2.", ["Scotch Game for White"]),
  lineFromMoves(3, "scotch-white", "Scotch Game for White — Line 3", ["e4","e5","Nf3","Nc6","d4","Qf6","Be3","Ke7","Nc3","Qh4","b4","Kd8","Qd2","Qg4","Bc4","Qxf3","Qd3","Qf6"], "Scotch Game analysis with interesting sidelines and simple plans. Line 3.", ["Scotch Game for White"]),
  lineFromMoves(4, "scotch-white", "Scotch Game for White — Line 4", ["e4","e5","Nf3","Nc6","d4","Qg5","Qd2","Qh4","Kd1","Qe7","Na3","Nf6","Ke1","h5","Nb5","exd4","Qc3","Qd6"], "Scotch Game analysis with interesting sidelines and simple plans. Line 4.", ["Scotch Game for White"]),
  lineFromMoves(5, "scotch-white", "Scotch Game for White — Line 5", ["e4","e5","Nf3","Nc6","d4","Qh4","Qd2","Qh3","Be2","Qxf3","Kf1","h6","Qb4","Qxe4","f4","Qxd4","Qxf8+","Kxf8"], "Scotch Game analysis with interesting sidelines and simple plans. Line 5.", ["Scotch Game for White"]),
  lineFromMoves(6, "scotch-white", "Scotch Game for White — Line 6", ["e4","e5","Nf3","Nc6","d4","Ke7","Bh6","d6","Nc3","Bg4","b3","Na5","Rb1","Bc8","Rc1","Nxh6","Nb5","g6"], "Scotch Game analysis with interesting sidelines and simple plans. Line 6.", ["Scotch Game for White"]),
  lineFromMoves(7, "scotch-white", "Scotch Game for White — Line 7", ["e4","e5","Nf3","Nc6","d4","Be7","Qd2","h5","Kd1","Kf8","Ke1","d6","dxe5","Nh6","g4","Bf5","g5","Bc8"], "Scotch Game analysis with interesting sidelines and simple plans. Line 7.", ["Scotch Game for White"]),
  lineFromMoves(8, "scotch-white", "Scotch Game for White — Line 8", ["e4","e5","Nf3","Nc6","d4","Bd6","Qd3","Nb8","c4","Kf8","Bh6","Qh4","Kd1","Qf4","Qa3","Nxh6","h3","Qh2"], "Scotch Game analysis with interesting sidelines and simple plans. Line 8.", ["Scotch Game for White"]),
  lineFromMoves(9, "scotch-white", "Scotch Game for White — Line 9", ["e4","e5","Nf3","Nc6","d4","Bc5","Qd2","b5","Be2","d5","h3","Bb6","Nc3","Qe7","exd5","g6","Rg1","Bxd4"], "Scotch Game analysis with interesting sidelines and simple plans. Line 9.", ["Scotch Game for White"]),
  lineFromMoves(10, "scotch-white", "Scotch Game for White — Line 10", ["e4","e5","Nf3","Nc6","d4","Bb4+","c3","f6","Bc4","b6","cxb4","Nxb4","Bf1","Ne7","a4","h6","h4","Nd3+"], "Scotch Game analysis with interesting sidelines and simple plans. Line 10.", ["Scotch Game for White"]),
  lineFromMoves(11, "scotch-white", "Scotch Game for White — Line 11", ["e4","e5","Nf3","Nc6","d4","Ba3","Bd3","f5","Bh6","Nb4","Nc3","Kf8","Be2","d5","g3","Nf6","Qd3","Qd7"], "Scotch Game analysis with interesting sidelines and simple plans. Line 11.", ["Scotch Game for White"]),
  lineFromMoves(12, "scotch-white", "Scotch Game for White — Line 12", ["e4","e5","Nf3","Nc6","d4","Nh6","Be2","Nxd4","Kd2","f5","b4","Nxf3+","Kd3","Qf6","Qf1","Ng5","Kc4","Nhf7"], "Scotch Game analysis with interesting sidelines and simple plans. Line 12.", ["Scotch Game for White"]),
  lineFromMoves(13, "scotch-white", "Scotch Game for White — Line 13", ["e4","e5","Nf3","Nc6","d4","Nf6","Bd3","Nxe4","Qd2","a5","h4","Bb4","Rh2","Nd6","Be2","Ra6","Nc3","h5"], "Scotch Game analysis with interesting sidelines and simple plans. Line 13.", ["Scotch Game for White"]),
  lineFromMoves(14, "scotch-white", "Scotch Game for White — Line 14", ["e4","e5","Nf3","Nc6","d4","Nge7","Bc4","Nxd4","Nbd2","Nef5","a4","c6","Nxe5","Ba3","Bb5","Ne2","Qxe2","c5"], "Scotch Game analysis with interesting sidelines and simple plans. Line 14.", ["Scotch Game for White"]),
  lineFromMoves(15, "scotch-white", "Scotch Game for White — Line 15", ["e4","e5","Nf3","Nc6","d4","a6","Bb5","h5","Bd2","Nb8","Bh6","gxh6","O-O","Bd6","Nc3","h4","h3","Nc6"], "Scotch Game analysis with interesting sidelines and simple plans. Line 15.", ["Scotch Game for White"]),
  lineFromMoves(16, "scotch-white", "Scotch Game for White — Line 16", ["e4","e5","Nf3","Nc6","d4","a5","Ba6","f5","Be3","h5","c4","Na7","Qd2","Nh6","Bxh6","gxh6","dxe5","Bc5"], "Scotch Game analysis with interesting sidelines and simple plans. Line 16.", ["Scotch Game for White"]),
  lineFromMoves(17, "scotch-white", "Scotch Game for White — Line 17", ["e4","e5","Nf3","Nc6","d4","b6","Rg1","h5","a3","Nxd4","Bf4","Ne7","Nh4","Ne6","Qd6","f5","Bd3","g6"], "Scotch Game analysis with interesting sidelines and simple plans. Line 17.", ["Scotch Game for White"]),
  lineFromMoves(18, "scotch-white", "Scotch Game for White — Line 18", ["e4","e5","Nf3","Nc6","d4","b5","Nxe5","Nb8","Bh6","Ne7","c4","Ng8","a3","Bb7","b3","Nf6","Qg4","Ke7"], "Scotch Game analysis with interesting sidelines and simple plans. Line 18.", ["Scotch Game for White"]),
];
