import { mkLine, lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION =
  "The Sicilian Defense: 1.e4 c5 — thirty-eight lines covering the Open Sicilian, Dragon, Najdorf, Alapin transpositions, and anti-anti-Sicilian setups.";

export default [
  mkLine(
    1,
    "sicilian_open",
    "Open Sicilian — ...Nc6",
    "Line #1 · Main Open Sicilian",
    "The Open Sicilian is the real deal: ...c5, ...d6, ...Nc6, and fight for the center.",
    ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","Nc6","Be3","e6","Qd2","a6","O-O-O","Bd7","f4","b5"],
    [
      "e4.",
      "...c5! — Sicilian!",
      "Nf3.",
      "...d6 — flexible.",
      "d4.",
      "...cxd4 trade.",
      "Nxd4.",
      "...Nf6 — develop.",
      "Nc3.",
      "...Nc6 — classical.",
      "Be3.",
      "...e6 — solid.",
      "Qd2.",
      "...a6 — Najdorf hybrid.",
      "O-O-O.",
      "...Bd7.",
      "f4.",
      "...b5 — queenside counter!",
    ],
    ["Sicilian Defense","Open"]
  ),
  mkLine(
    2,
    "sicilian_dragon",
    "Dragon — ...g6 and ...Bg7",
    "Line #2 · Yugoslav Attack",
    "The Dragon fianchettos the bishop and attacks on the kingside.",
    ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","g6","Be3","Bg7","f3","O-O","Qd2","Nc6","O-O-O","Bd7","g4","Rc8"],
    [
      "e4.",
      "...c5!",
      "Nf3.",
      "...d6.",
      "d4.",
      "...cxd4.",
      "Nxd4.",
      "...Nf6.",
      "Nc3.",
      "...g6 — Dragon!",
      "Be3.",
      "...Bg7 — bishop breathes fire.",
      "f3.",
      "...O-O.",
      "Qd2.",
      "...Nc6.",
      "O-O-O.",
      "...Bd7.",
      "g4.",
      "...Rc8 — pressure c-file.",
    ],
    ["Sicilian Defense","Dragon"]
  ),
  mkLine(
    3,
    "sicilian_najdorf",
    "Najdorf — ...a6",
    "Line #3 · Najdorf main",
    "...a6 is the Najdorf — flexible, deep, and fighting.",
    ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Be3","e5","Nb3","Be6","f3","Be7","Qd2","O-O","O-O-O","b5"],
    [
      "e4.",
      "...c5!",
      "Nf3.",
      "...d6.",
      "d4.",
      "...cxd4.",
      "Nxd4.",
      "...Nf6.",
      "Nc3.",
      "...a6 — Najdorf!",
      "Be3.",
      "...e5 — kick the knight.",
      "Nb3.",
      "...Be6.",
      "f3.",
      "...Be7.",
      "Qd2.",
      "...O-O.",
      "O-O-O.",
      "...b5 — queenside space.",
    ],
    ["Sicilian Defense","Najdorf"]
  ),
  lineFromMoves(4, "sicilian", "Alapin 2.c3 d5", ["e4","c5","c3","d5","exd5","Qxd5","d4","Nf6","Nf3","e6","Be2","Nc6","O-O","Be7","Re1","O-O"], "Alapin with ...d5 — equal and solid.", ["Sicilian Defense","Alapin"]),
  lineFromMoves(5, "sicilian", "Alapin 2.c3 Nf6", ["e4","c5","c3","Nf6","e5","Nd5","d4","cxd4","cxd4","e6","Nf3","d6","Bc4","Nb6","Bb3","N8d7"], "Alapin ...Nf6 — ...Nb6 reroute.", ["Sicilian Defense","Alapin"]),
  mkLine(
    6,
    "sicilian_scheveningen",
    "Scheveningen — ...e6",
    "Line #6 · Scheveningen setup",
    "The Scheveningen with ...e6 is rock solid and flexible.",
    ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","e6","Be3","a6","f3","b5","Qd2","Bb7","O-O-O","Nbd7","g4","b4"],
    [
      "e4.",
      "...c5!",
      "Nf3.",
      "...d6.",
      "d4.",
      "...cxd4.",
      "Nxd4.",
      "...Nf6.",
      "Nc3.",
      "...e6 — Scheveningen!",
      "Be3.",
      "...a6.",
      "f3.",
      "...b5.",
      "Qd2.",
      "...Bb7.",
      "O-O-O.",
      "...Nbd7.",
      "g4.",
      "...b4 — kick the knight.",
    ],
    ["Sicilian Defense","Scheveningen"]
  ),
  lineFromMoves(7, "sicilian", "Closed 2.Nc3 Nc6", ["e4","c5","Nc3","Nc6","f4","g6","Nf3","Bg7","Bb5","Nd4","Bxd7+","Qxd7","O-O","e6","d3","Nge7"], "Closed Sicilian — ...Nc6 and ...g6.", ["Sicilian Defense","Closed"]),
  lineFromMoves(8, "sicilian", "Rossolimo 3.Bb5", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","Nc6","Ndb5","Bd7","Nxd6+","exd6","Nd5","Be7"], "Rossolimo ...g6 — solid fianchetto.", ["Sicilian Defense","Rossolimo"]),
  mkLine(
    9,
    "sicilian_accel_dragon",
    "Accelerated Dragon — ...g6 early",
    "Line #9 · Accelerated Dragon",
    "Play ...g6 before ...d6 for faster Dragon setups.",
    ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","g6","Nc3","Bg7","Be3","Nf6","f3","O-O","Qd2","d6","O-O-O","Bd7","g4","Rc8"],
    [
      "e4.",
      "...c5!",
      "Nf3.",
      "...Nc6.",
      "d4.",
      "...cxd4.",
      "Nxd4.",
      "...g6 — Accelerated!",
      "Nc3.",
      "...Bg7.",
      "Be3.",
      "...Nf6.",
      "f3.",
      "...O-O.",
      "Qd2.",
      "...d6.",
      "O-O-O.",
      "...Bd7.",
      "g4.",
      "...Rc8.",
    ],
    ["Sicilian Defense","Accelerated Dragon"]
  ),
  lineFromMoves(10, "sicilian", "Taimanov 2...Nc6", ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","e6","Nc3","Qc7","Be2","a6","O-O","Nf6","Be3","Bb4"], "Taimanov ...Nc6 and ...Qc7.", ["Sicilian Defense","Taimanov"]),
  lineFromMoves(11, "sicilian", "Kan 2...e6", ["e4","c5","Nf3","e6","d4","cxd4","Nxd4","a6","Nc3","Qc7","Be2","Nf6","O-O","Bb4","Qd3","O-O"], "Kan ...e6 and ...a6.", ["Sicilian Defense","Kan"]),
  lineFromMoves(12, "sicilian", "Moscow 3.Bb5+", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Bb5+","Bd7","Bxd7+","Qxd7","Nc3","g6","O-O","Nc6","Ndb5","O-O-O"], "Moscow Bb5+ — trade and fianchetto.", ["Sicilian Defense"]),
  lineFromMoves(13, "sicilian", "Paulsen — ...a6 and ...e6", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","g6","Ndb5","Nbd7","Nxd6+","exd6","Nd5","Bg7","Ne7","Nf8","Nxc8","Ne6"], "The Paulsen setup is flexible and safe.", ["Sicilian Defense","Paulsen"]),
  lineFromMoves(14, "sicilian", "Grand Prix 2.f4", ["e4","c5","f4","d6","Nf3","Nf6","Nc3","g6","Bb5+","Bd7","Bxd7+","Qxd7","O-O","Bg7","d3","O-O"], "Grand Prix f4 — ...g6 and fianchetto.", ["Sicilian Defense"]),
  lineFromMoves(15, "sicilian", "Smith-Morra 2.d4", ["e4","c5","d4","cxd4","c3","dxc3","Nxc3","Nc6","Nf3","d6","Bc4","e6","O-O","a6","Qe2","Nf6"], "Smith-Morra gambit — develop with ...Nc6.", ["Sicilian Defense"]),
  lineFromMoves(16, "sicilian", "Najdorf 6.Be3 e5", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Be3","e5","Nb3","Be6","f3","Be7","Qd2","O-O"], "Najdorf Be3 — full tabiya.", ["Sicilian Defense","Najdorf"]),
  mkLine(
    17,
    "sicilian_sveshnikov",
    "Sveshnikov — ...e5",
    "Line #17 · Sveshnikov",
    "The Sveshnikov ...e5 is sharp but well-tested.",
    ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","Nf6","Nc3","e5","Ndb5","d6","Bg5","a6","Na3","b5","Nd5","Be7","Bxf6","Bxf6","c3","O-O"],
    [
      "e4.",
      "...c5!",
      "Nf3.",
      "...Nc6.",
      "d4.",
      "...cxd4.",
      "Nxd4.",
      "...Nf6.",
      "Nc3.",
      "...e5! — Sveshnikov!",
      "Ndb5.",
      "...d6.",
      "Bg5.",
      "...a6.",
      "Na3.",
      "...b5.",
      "Nd5.",
      "...Be7.",
      "Bxf6.",
      "...Bxf6.",
      "c3.",
      "...O-O.",
    ],
    ["Sicilian Defense","Sveshnikov"]
  ),
  lineFromMoves(18, "sicilian", "Dragon 9...Bd7", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","g6","Be3","Bg7","f3","O-O","Qd2","Nc6","O-O-O","Bd7","g4","Rc8"], "Dragon Bd7 — Yugoslav tabiya.", ["Sicilian Defense","Dragon"]),
  lineFromMoves(19, "sicilian", "Alapin 2.c3 d5 Exchange", ["e4","c5","c3","d5","exd5","Qxd5","d4","Nf6","Nf3","Bg4","Be2","e6","O-O","Nc6","Be3","cxd4"], "Alapin ...Bg4 pin.", ["Sicilian Defense","Alapin"]),
  lineFromMoves(20, "sicilian", "2.Nc3 Nc6", ["e4","c5","Nc3","Nc6","f4","g6","Nf3","Bg7","Bb5","Nd4","Bxd7+","Qxd7","O-O","e6","d3","Nge7","Qe1","O-O"], "Closed Nc3 — solid development.", ["Sicilian Defense"]),
  mkLine(
    21,
    "sicilian_classical",
    "Classical — ...Nc6 and ...d6",
    "Line #21 · Classical Sicilian",
    "The classical ...Nc6 and ...d6 is timeless.",
    ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","Nc6","Be2","e6","O-O","Be7","Be3","O-O","Nb3","b6","f4","Bb7"],
    [
      "e4.",
      "...c5!",
      "Nf3.",
      "...d6.",
      "d4.",
      "...cxd4.",
      "Nxd4.",
      "...Nf6.",
      "Nc3.",
      "...Nc6 — classical!",
      "Be2.",
      "...e6.",
      "O-O.",
      "...Be7.",
      "Be3.",
      "...O-O.",
      "Nb3.",
      "...b6.",
      "f4.",
      "...Bb7.",
    ],
    ["Sicilian Defense","Classical"]
  ),
  lineFromMoves(22, "sicilian", "Najdorf 7.f3 Be7", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Be3","e5","Nb3","Be6","f3","Be7","Qd2","O-O","O-O-O","b5"], "Najdorf f3 — queenside expansion.", ["Sicilian Defense","Najdorf"]),
  lineFromMoves(23, "sicilian", "Rossolimo 3.Bb5 Nd4", ["e4","c5","Nf3","Nc6","Bb5","Nd4","Nxd4","cxd4","O-O","g6","d3","Bg7","Nd2","e6","f4","Ne7"], "Rossolimo Nd4 — central knight.", ["Sicilian Defense","Rossolimo"]),
  lineFromMoves(24, "sicilian", "Hyperaccel Dragon", ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","g6","Nc3","Bg7","Be3","Nf6","f3","O-O","Qd2","d6","O-O-O","Nxd4","Bxd4","Be6"], "Hyperaccelerated Dragon — fast setup.", ["Sicilian Defense","Dragon"]),
  lineFromMoves(25, "sicilian", "2.c3 Alapin g6", ["e4","c5","c3","Nf6","e5","Nd5","d4","cxd4","cxd4","e6","Nf3","d6","Bc4","Nb6","Bb3","Nc6"], "Alapin against ...Nf6.", ["Sicilian Defense","Alapin"]),
  mkLine(
    26,
    "sicilian_pelikan",
    "Pelikan/Sveshnikov — ...e5",
    "Line #26 · Pelikan variation",
    "The Pelikan is the Sveshnikov's wild cousin.",
    ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","Nf6","Nc3","e5","Ndb5","d6","Bg5","a6","Na3","b5","Bxf6","gxf6","Nd5","f5","c3","Bg7"],
    [
      "e4.",
      "...c5!",
      "Nf3.",
      "...Nc6.",
      "d4.",
      "...cxd4.",
      "Nxd4.",
      "...Nf6.",
      "Nc3.",
      "...e5!",
      "Ndb5.",
      "...d6.",
      "Bg5.",
      "...a6.",
      "Na3.",
      "...b5.",
      "Bxf6.",
      "...gxf6 — open g-file!",
      "Nd5.",
      "...f5.",
      "c3.",
      "...Bg7.",
    ],
    ["Sicilian Defense","Pelikan"]
  ),
  lineFromMoves(27, "sicilian", "Dragon 10.h4", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","g6","Be3","Bg7","f3","O-O","Qd2","Nc6","O-O-O","Bd7","h4","Rc8"], "Dragon h4 — ...Rc8 pressure.", ["Sicilian Defense","Dragon"]),
  lineFromMoves(28, "sicilian", "4...a6 Scheveningen", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Be2","e6","O-O","Be7","f4","Qc7","Kh1","b5"], "Scheveningen a6 — flexible.", ["Sicilian Defense"]),
  lineFromMoves(29, "sicilian", "Prins 2.a3", ["e4","c5","a3","Nc6","d4","cxd4","Qxd4","Nf6","Qd3","g6","Nc3","Bg7","Be2","O-O","Nf3","d6"], "Anti-Sicilian a3 — normal development.", ["Sicilian Defense"]),
  lineFromMoves(30, "sicilian", "Najdorf 8.Qd2 b5", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Be3","e5","Nb3","Be6","f3","Be7","Qd2","O-O","O-O-O","b5","Kb1","Nbd7"], "Full Najdorf tabiya.", ["Sicilian Defense","Najdorf"]),
  lineFromMoves(31, "sicilian", "Kalashnikov — ...e5 and ...b5", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Ndb5","Nbd7","Nxd6+","exd6","Nd5","Be7","Nxe7","Nf8","Nxc8","Ng6"], "The Kalashnikov with ...e5 and ...b5 is aggressive.", ["Sicilian Defense","Kalashnikov"]),
  lineFromMoves(32, "sicilian", "2.b3 Snyder", ["e4","c5","c3","d5","exd5","Qxd5","d4","Nf6","Nf3","e6","Ne5","Nbd7","Nxd7","Bxd7","Nd2","O-O-O"], "Snyder b3 — fianchetto response.", ["Sicilian Defense"]),
  lineFromMoves(33, "sicilian", "Dragon 11.Kb1", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","g6","Be3","Bg7","f3","O-O","Qd2","Nc6","O-O-O","Bd7","Kb1","Rc8","g4","Ne5"], "Dragon Kb1 — ...Ne5 centralize.", ["Sicilian Defense","Dragon"]),
  lineFromMoves(34, "sicilian", "Alapin 2.c3 e6", ["e4","c5","c3","e6","d4","d5","exd5","Qxd5","Nf3","Nf6","Be2","Nc6","O-O","Be7","Re1","O-O"], "Alapin ...e6 — French-like structure.", ["Sicilian Defense","Alapin"]),
  lineFromMoves(35, "sicilian", "Open 6.f4", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","Nc6","Be3","e6","Qd2","a6","O-O-O","Bd7","f4","b5","e5","dxe5"], "Open f4 — ...b5 counter.", ["Sicilian Defense"]),
  lineFromMoves(36, "sicilian", "Najdorf 9.g4", ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Be3","e5","Nb3","Be6","f3","Be7","Qd2","O-O","O-O-O","b5","g4","b4"], "Najdorf g4 — ...b4 kick.", ["Sicilian Defense","Najdorf"]),
  lineFromMoves(37, "sicilian", "2.d4 Smith-Morra", ["e4","c5","d4","cxd4","c3","dxc3","Nxc3","Nc6","Nf3","d6","Bc4","e6","O-O","a6","Qe2","Nf6","Rd1","Be7"], "Morra gambit — solid development.", ["Sicilian Defense"]),
  lineFromMoves(38, "sicilian", "Fortress Classical", ["e4","c5","c3","Nf6","e5","Nd5","d4","cxd4","cxd4","e6","Nd2","Be7","Ne4","O-O","Nd6","Bf6","Nxb7","Bxb7","Bd2","Bc8","Bc3","Bb7"], "Full classical review — your Sicilian backbone.", ["Sicilian Defense"]),
];
