import { mkLine, lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION =
  "The Traxler Counterattack: 1.e4 e5 2.Nf3 Nc6 3.Bc4 Nf6 4.Ng5 Bc5! — twenty-six wild lines punishing the Fried Liver with sacrificial chaos.";

export default [
  mkLine(
    1,
    "traxler_main",
    "Main Line — ...Bc5!",
    "Line #1 · Traxler core",
    "White plays Ng5? You ignore the threat and play ...Bc5! — the Traxler way.",
    ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","g3","Nxg3","hxg3","Qxg3+","Kf1","Rf8"],
    [
      "e4.",
      "...e5.",
      "Nf3.",
      "...Nc6.",
      "Bc4.",
      "...Nf6 — invite Ng5.",
      "Ng5 — Fried Liver!",
      "...Bc5! — Traxler!",
      "Nxf7.",
      "...Bxf2+ — sacrifice!",
      "Kxf2.",
      "...Nxe4+ — fork.",
      "Kg1.",
      "...Qh4 — queen enters.",
      "g3.",
      "...Nxg3!",
      "hxg3.",
      "...Qxg3+.",
      "Kf1.",
      "...Rf8 — rook joins.",
    ],
    ["Traxler Counterattack","Main Line"]
  ),
  lineFromMoves(2, "traxler", "Bishop f2 Sacrifice", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","d3","Ng3","hxg3","Qxg3+","Kf1","Rf8"], "The ...Bxf2+ sacrifice is the heart of the Traxler. Know the follow-ups.", ["Traxler Counterattack"]),
  lineFromMoves(3, "traxler", "5.Bxf7+ Decline", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","Qe2","Ng3","hxg3","Qh3","Kf1","Rf8"], "If White takes with bishop, ...Kxf7 and ...Nxe5.", ["Traxler Counterattack"]),
  lineFromMoves(4, "traxler", "6.d4 Defense", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","g3","Nxg3","hxg3","Qxg3+","Kf1","d5"], "d4 defense — same attacking pattern.", ["Traxler Counterattack"]),
  lineFromMoves(5, "traxler", "Queen h4 — Attack", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","Nc3","Ng3","hxg3","Qxg3+","Kf1","Rf8"], "The queen on h4 creates mating threats everywhere.", ["Traxler Counterattack","Tactics"]),
  lineFromMoves(6, "traxler", "7.Qe2 Block", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","Bd5","Ng3","hxg3","Qxg3+","Kf1","Rf8"], "Qe2 block — keep attacking with ...Qh3.", ["Traxler Counterattack"]),
  lineFromMoves(7, "traxler", "4.d3 Avoidance", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","c3","Ng3","hxg3","Qxg3+","Kf1","Rf8"], "If White avoids with d3, still play ...Bc5.", ["Traxler Counterattack"]),
  mkLine(
    8,
    "traxler_nxg3",
    "Knight g3 Sacrifice",
    "Line #8 · ...Nxg3 hook",
    "The ...Nxg3 sacrifice opens the h-file for your queen.",
    ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","g3","Nxg3","hxg3","Qxg3+","Kf1","Rf8","Qf3","d5"],
    [
      "e4.",
      "...e5.",
      "Nf3.",
      "...Nc6.",
      "Bc4.",
      "...Nf6.",
      "Ng5.",
      "...Bc5!",
      "Nxf7.",
      "...Bxf2+!",
      "Kxf2.",
      "...Nxe4+.",
      "Kg1.",
      "...Qh4.",
      "g3.",
      "...Nxg3!",
      "hxg3.",
      "...Qxg3+.",
      "Kf1.",
      "...Rf8.",
      "Qf3.",
      "...d5.",
    ],
    ["Traxler Counterattack"]
  ),
  lineFromMoves(9, "traxler", "5.Nxf7 Bxf2+", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","a3","Ng3","hxg3","Qxg3+","Kf1","Rf8"], "Core Traxler position — drill it.", ["Traxler Counterattack"]),
  lineFromMoves(10, "traxler", "6.Kg1 King Walk", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","b3","Ng3","hxg3","Qxg3+","Kf1","Rf8"], "King walk on g1 — keep pressure.", ["Traxler Counterattack"]),
  lineFromMoves(11, "traxler", "8.Nf3 Block", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","d4","Ng3","hxg3","Qxg3+","Kf1","Rf8"], "Nf3 block — rook to f8.", ["Traxler Counterattack"]),
  lineFromMoves(12, "traxler", "Central ...d5", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","d3","Ng3","hxg3","Qxg3+","Kf1","Rf8"], "...d5 appears in many Traxler lines — blast the center open.", ["Traxler Counterattack"]),
  lineFromMoves(13, "traxler", "4.d4 Italian", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","Qe2","Ng3","hxg3","Qh3","Kf1","Rf8"], "Italian d4 — Traxler still works.", ["Traxler Counterattack"]),
  lineFromMoves(14, "traxler", "7.Be3 Solid", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","g3","Nxg3","hxg3","Qxg3+","Kf1","d5"], "Be3 solid — same attack.", ["Traxler Counterattack"]),
  lineFromMoves(15, "traxler", "5.Bd5 Sideline", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","Nc3","Ng3","hxg3","Qxg3+","Kf1","Rf8"], "Bd5 sideline — take the rook anyway.", ["Traxler Counterattack"]),
  lineFromMoves(16, "traxler", "9.Kf1 King Hunt", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","Bd5","Ng3","hxg3","Qxg3+","Kf1","Rf8"], "King hunt on f1 — keep attacking.", ["Traxler Counterattack"]),
  lineFromMoves(17, "traxler", "Wilkes-Barre — ...Bb4", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","c3","Ng3","hxg3","Qxg3+","Kf1","Rf8"], "Some Traxler players prefer ...Bb4 — know both.", ["Traxler Counterattack"]),
  lineFromMoves(18, "traxler", "6.h3 Block", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","a3","Ng3","hxg3","Qxg3+","Kf1","Rf8"], "h3 block — fxg3 recapture.", ["Traxler Counterattack"]),
  lineFromMoves(19, "traxler", "8.Qf3 Defense", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","b3","Ng3","hxg3","Qxg3+","Kf1","Rf8"], "Qf3 defense — ...Qh3 mate threat.", ["Traxler Counterattack"]),
  lineFromMoves(20, "traxler", "4.O-O Decline", ["e4","e5","Nf3","Nc6","Bc4","Nf6","O-O","Nxe4","Re1","d5","Bxd5","Qxd5","Nc3","Qd8","Nxe4","Be7"], "If White declines Ng5, grab on e4.", ["Traxler Counterattack"]),
  lineFromMoves(21, "traxler", "7.Nc3 Develop", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","d4","Ng3","hxg3","Qxg3+","Kf1","Rf8"], "Nc3 develop — same attack.", ["Traxler Counterattack"]),
  lineFromMoves(22, "traxler", "5.Nxh8 Greed", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","Nxh8","Ne7","Ng6","Ng8"], "If White grabs hxh8, keep sacrificing.", ["Traxler Counterattack"]),
  lineFromMoves(23, "traxler", "9.exd5 Central", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","d3","O-O","Nh8+","Rf7","Ng6","Ne7","Nxe7+","Qxe7","Bb5","Nd6"], "Full d5 central break.", ["Traxler Counterattack"]),
  lineFromMoves(24, "traxler", "3...Bc5 Early", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","Qe2","O-O"], "Early ...Bc5 before Nf6 — same ideas.", ["Traxler Counterattack"]),
  lineFromMoves(25, "traxler", "10.Bg5 Pin", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","Qe2","O-O","Nh8+","Rf7","Ng6","Ne7","Nxe7+","Qxe7"], "Bg5 pin — kick with ...h6.", ["Traxler Counterattack"]),
  lineFromMoves(26, "traxler", "Quiet 4.d3", ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5","Nxf7","Bxf2+","Kxf2","Nxe4+","Kg1","Qh4","Nxh8","Ne7","Ng6","Ng8"], "Delayed Traxler when White plays d3 first.", ["Traxler Counterattack"]),
];
