import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines.";

/** Potluck course — generated from validated templates. */
export default [
  lineFromMoves(1, "vienna-full", "FULL Vienna Gambit — Line 1", ["e4","e5","Nc3","Nf6","f4","Nc6","Kf2","g6","Qe2","Nb4","Nb5","Rb8","Na3","Bg7","Nf3","c5","Kg3","Qb6"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 1.", ["FULL Vienna Gambit"]),
  lineFromMoves(2, "vienna-full", "FULL Vienna Gambit — Line 2", ["e4","e5","Nc3","Nf6","f4","Na6","Be2","Nc5","b4","Rb8","Bd3","d6","Ba6","Nfd7","Bxb7","Nd3+","Ke2","g5"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 2.", ["FULL Vienna Gambit"]),
  lineFromMoves(3, "vienna-full", "FULL Vienna Gambit — Line 3", ["e4","e5","Nc3","Nf6","f4","Qe7","Bd3","h5","Nd5","Rg8","Ne2","b5","g4","c6","Nb6","Nxe4","c3","exf4"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 3.", ["FULL Vienna Gambit"]),
  lineFromMoves(4, "vienna-full", "FULL Vienna Gambit — Line 4", ["e4","e5","Nc3","Nf6","f4","Ke7","Bc4","Rg8","h3","Nd5","Nf3","g5","Nxg5","Kd6","Nb1","Nc6","O-O","Ndb4"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 4.", ["FULL Vienna Gambit"]),
  lineFromMoves(5, "vienna-full", "FULL Vienna Gambit — Line 5", ["e4","e5","Nc3","Nf6","f4","Be7","Bb5","Na6","Ke2","h5","a3","exf4","h4","Nc5","Nd5","Nb3","Nxc7+","Kf8"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 5.", ["FULL Vienna Gambit"]),
  lineFromMoves(6, "vienna-full", "FULL Vienna Gambit — Line 6", ["e4","e5","Nc3","Nf6","f4","Bd6","Ba6","Nxe4","Nf3","f6","Kf1","Ke7","Bxb7","Re8","Ke1","h5","Nxe5","Kf8"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 6.", ["FULL Vienna Gambit"]),
  lineFromMoves(7, "vienna-full", "FULL Vienna Gambit — Line 7", ["e4","e5","Nc3","Nf6","f4","Bc5","Nh3","c6","a4","d6","Ra2","Ba3","Bd3","Qa5","Ne2","d5","Ng3","Bg4"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 7.", ["FULL Vienna Gambit"]),
  lineFromMoves(8, "vienna-full", "FULL Vienna Gambit — Line 8", ["e4","e5","Nc3","Nf6","f4","Bb4","f5","h5","Qe2","Nd5","Qg4","Rg8","h4","Bxc3","Bd3","g6","Rb1","f6"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 8.", ["FULL Vienna Gambit"]),
  lineFromMoves(9, "vienna-full", "FULL Vienna Gambit — Line 9", ["e4","e5","Nc3","Nf6","f4","Ba3","fxe5","Ng4","Bb5","Nxe5","d3","Bb4","Ne2","Bc5","Rf1","Bd6","Rxf7","c5"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 9.", ["FULL Vienna Gambit"]),
  lineFromMoves(10, "vienna-full", "FULL Vienna Gambit — Line 10", ["e4","e5","Nc3","Nf6","f4","Rg8","f5","Bc5","Qf3","Bf2+","Qxf2","Kf8","Nh3","c5","d4","Ne8","Ng1","Qg5"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 10.", ["FULL Vienna Gambit"]),
  lineFromMoves(11, "vienna-full", "FULL Vienna Gambit — Line 11", ["e4","e5","Nc3","Nf6","f4","a6","fxe5","Bb4","g3","Nc6","Qf3","Nxe4","g4","Ba3","Qe3","Nf6","Bg2","Rg8"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 11.", ["FULL Vienna Gambit"]),
  lineFromMoves(12, "vienna-full", "FULL Vienna Gambit — Line 12", ["e4","e5","Nc3","Nf6","f4","a5","Na4","Nc6","g4","Bd6","Bh3","g5","Nc3","Bb4","Kf2","Nb8","Nd5","Rf8"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 12.", ["FULL Vienna Gambit"]),
  lineFromMoves(13, "vienna-full", "FULL Vienna Gambit — Line 13", ["e4","e5","Nc3","Nf6","f4","b6","Nb5","Ba6","a3","Bc8","Rb1","exf4","b3","Rg8","d3","Qe7","Nd4","Qc5"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 13.", ["FULL Vienna Gambit"]),
  lineFromMoves(14, "vienna-full", "FULL Vienna Gambit — Line 14", ["e4","e5","Nc3","Nf6","f4","b5","Nb1","Na6","Kf2","h6","g4","Nxg4+","Kg2","d6","b3","d5","Nf3","f6"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 14.", ["FULL Vienna Gambit"]),
  lineFromMoves(15, "vienna-full", "FULL Vienna Gambit — Line 15", ["e4","e5","Nc3","Nc6","f3","Na5","Na4","Nh6","Ke2","Nf5","b4","d6","Nc5","Qf6","exf5","Qh6","f4","Qxf4"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 15.", ["FULL Vienna Gambit"]),
  lineFromMoves(16, "vienna-full", "FULL Vienna Gambit — Line 16", ["e4","e5","Nc3","Na6","g3","Qh4","Qf3","Qg5","Qf6","b5","d3","d6","Ke2","c6","Qxf7+","Kxf7","Ke1","Nb4"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 16.", ["FULL Vienna Gambit"]),
  lineFromMoves(17, "vienna-full", "FULL Vienna Gambit — Line 17", ["e4","e5","Nc3","Qe7","g4","b6","Bb5","h5","Ke2","Ba6","Rb1","Kd8","Ke3","f6","Be2","Kc8","Bc4","c6"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 17.", ["FULL Vienna Gambit"]),
  lineFromMoves(18, "vienna-full", "FULL Vienna Gambit — Line 18", ["e4","e5","Nc3","Qf6","h3","Qh6","Bc4","Qg6","d3","Qf5","Nb5","Nh6","Bb3","Qh5","Bd2","Nc6","Ne2","Ng8"], "Every variation from the Vienna Gambit — accepted, declined, and wild sidelines. Line 18.", ["FULL Vienna Gambit"]),
];
