import { mkLine, lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION =
  "Counter the Vienna Gambit: 1.e4 e5 2.Nc3 Nf6 3.f4 d5 — fourteen lines punishing White's aggressive f4 push.";

export default [
  mkLine(
    1,
    "vienna_counter_main",
    "Main Line — ...d5 Strike",
    "Line #1 · Classical counter",
    "White plays the Vienna Gambit with f4? Your ...d5 breaks it open immediately.",
    ["e4","e5","Nc3","Nf6","f4","d5","fxe5","Nxe4","Nf3","Bg4","Be2","Nc6","O-O","Be7","d4","O-O"],
    [
      "e4.",
      "...e5 — classical center.",
      "Nc3.",
      "...Nf6 — Vienna Game setup.",
      "f4 — the gambit!",
      "...d5! — best! Strike the center now.",
      "fxe5.",
      "...Nxe4 — knight jumps in.",
      "Nf3.",
      "...Bg4 pins — classic Vienna counter.",
      "Be2.",
      "...Nc6 develops.",
      "O-O.",
      "...Be7 — ready to castle.",
      "d4.",
      "...O-O — solid king safety.",
    ],
    ["Vienna Gambit Counter","Main Line"]
  ),
  mkLine(
    2,
    "vienna_counter_dxe4",
    "3...dxe4 — Early Capture",
    "Line #2 · Grab e4 first",
    "Sometimes take on e4 before f4 — same fighting spirit.",
    ["e4","e5","Nc3","Nf6","f4","Nc6","fxe5","Nxe4","Nxe4","d5","d4","dxe4","Be3","Bf5"],
    [
      "e4.",
      "...e5.",
      "Nc3.",
      "...Nf6.",
      "f4.",
      "...Nc6 — support e5.",
      "fxe5.",
      "...Nxe4!",
      "Nxe4.",
      "...d5 — fork the knights!",
      "d4.",
      "...dxe4.",
      "Be3.",
      "...Bf5 — bishop active.",
    ],
    ["Vienna Gambit Counter"]
  ),
  lineFromMoves(3, "vienna-counter", "4.exd5 Nxd5", ["e4","e5","Nc3","Nf6","f4","d5","exd5","Nxd5","fxe5","Nxc3","bxc3","Qh4+","g3","Qe4+"], "If White takes d5 with the pawn, ...Nxd5 and ...Qh4+.", ["Vienna Gambit Counter"]),
  lineFromMoves(4, "vienna-counter", "5.d3 Defense", ["e4","e5","Nc3","Nf6","f4","d5","fxe5","Nxe4","d3","Nc5","d4","Ne6","Nf3","Nc6"], "White plays d3 — retreat knight and keep pieces.", ["Vienna Gambit Counter"]),
  mkLine(
    5,
    "vienna_counter_ng5",
    "vs 5.Ng5",
    "Line #5 · Handle the attack",
    "White gets aggressive with Ng5 — stay calm with ...Nxc3.",
    ["e4","e5","Nc3","Nf6","f4","d5","fxe5","Nxe4","Nf3","Bg4","Ng5","Nxc3","bxc3","Qe7","Be2","Nd7"],
    [
      "e4.",
      "...e5.",
      "Nc3.",
      "...Nf6.",
      "f4.",
      "...d5!",
      "fxe5.",
      "...Nxe4.",
      "Nf3.",
      "...Bg4.",
      "Ng5 — aggressive!",
      "...Nxc3 — trade off the attacker.",
      "bxc3.",
      "...Qe7 — connect rooks.",
      "Be2.",
      "...O-O-O — castle long for counterplay.",
    ],
    ["Vienna Gambit Counter"]
  ),
  lineFromMoves(6, "vienna-counter", "4.Nxe4 dxe4", ["e4","e5","Nc3","Nf6","f4","d5","fxe5","Nxe4","Nf3","Bg4","Be2","Nc6","O-O","Be7"], "Trade on e4 and play ...Nc6.", ["Vienna Gambit Counter"]),
  lineFromMoves(7, "vienna-counter", "3.f4 exf4", ["e4","e5","Nc3","Nf6","f4","exf4","e5","Qe7","Nf3","d5","d4","Ng4","Be2","Nc6"], "If White's pawn takes on f4, ...Qe7 and ...d5.", ["Vienna Gambit Counter"]),
  lineFromMoves(8, "vienna-counter", "6.Bc4 Bc5", ["e4","e5","Nc3","Nf6","f4","d5","fxe5","Nxe4","Nf3","Bg4","Bc4","Bc5","Bb5+","Nd7"], "Meet Bc4 with ...Bc5 — easy development.", ["Vienna Gambit Counter"]),
  mkLine(
    9,
    "vienna_counter_qh4",
    "Queen to h4 — Tactical",
    "Line #9 · ...Qh4+ hook",
    "When White slips, ...Qh4+ can appear out of nowhere.",
    ["e4","e5","Nc3","Nf6","f4","d5","fxe5","Nxe4","Nf3","Bg4","Be2","Bxf3","Bxf3","Qh4+","g3","Nxg3"],
    [
      "e4.",
      "...e5.",
      "Nc3.",
      "...Nf6.",
      "f4.",
      "...d5!",
      "fxe5.",
      "...Nxe4.",
      "Nf3.",
      "...Bg4.",
      "Be2.",
      "...Bxf3 trade.",
      "Bxf3.",
      "...Qh4+!",
      "g3.",
      "...Nxg3 — winning!",
    ],
    ["Vienna Gambit Counter","Tactics"]
  ),
  lineFromMoves(10, "vienna-counter", "2.f4 Immediate", ["e4","e5","f4","exf4","Nf3","d5","exd5","Qxd5","d4","Nf6","Nc3","Bb4"], "Rare 2.f4 — answer with ...exf4 and ...d5.", ["Vienna Gambit Counter"]),
  lineFromMoves(11, "vienna-counter", "5.Qe2 Sideline", ["e4","e5","Nc3","Nf6","f4","d5","fxe5","Nxe4","Qe2","Bf5","Nf3","Nc6","d4","Bb4"], "White's Qe2 gets met by ...Bf5 and ...Nc6.", ["Vienna Gambit Counter"]),
  lineFromMoves(12, "vienna-counter", "7.c4 Center", ["e4","e5","Nc3","Nf6","f4","exf4","e5","Qe7","Nf3","d5","Nxd5","Nbd7","Nxc7+","Kd8","Ne8","Nxe5"], "If White pushes c4, develop with ...Nc6.", ["Vienna Gambit Counter"]),
  lineFromMoves(13, "vienna-counter", "Petrov-style 3.Nf3", ["e4","e5","Nc3","Nf6","Nf3","Nc6","Bb5","Bb4","O-O","O-O","d3","d6"], "When White avoids f4, normal Vienna/Petrov development.", ["Vienna Gambit Counter"]),
  lineFromMoves(14, "vienna-counter", "Gambit Declined 3.d3", ["e4","e5","Nc3","Nf6","d3","Nc6","f4","d5","fxe5","Nxe4","Nf3","Bg4","Be2","Be7"], "White delays f4 with d3 — still play ...d5 when f4 comes.", ["Vienna Gambit Counter"]),
];
