import { lineFromMoves } from "../repertoire-line-factory.mjs";

export const COURSE_DESCRIPTION = "Every gambit in one place — Danish, Vienna, King's Gambit, and more.";

/** Potluck course — generated from validated templates. */
export default [
  lineFromMoves(1, "white-gambits", "All My White Gambits — Line 1", ["e4","e5","d4","exd4","c3","Nc6","Bd2","Bb4","Qf3","a6","Bg5","Na5","Bd2","Nb3","g4","Ke7","Ke2","Na5"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 1.", ["All My White Gambits"]),
  lineFromMoves(2, "white-gambits", "All My White Gambits — Line 2", ["e4","e5","d4","exd4","c3","Na6","Be3","Nf6","b4","Rb8","f4","h6","Qd2","Ng4","Nh3","Ke7","Ng5","Nf6"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 2.", ["All My White Gambits"]),
  lineFromMoves(3, "white-gambits", "All My White Gambits — Line 3", ["e4","e5","d4","exd4","c3","Qe7","Bf4","Qd8","Bc1","f5","Na3","fxe4","Bf4","Bb4","Ne2","e3","g3","Qh4"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 3.", ["All My White Gambits"]),
  lineFromMoves(4, "white-gambits", "All My White Gambits — Line 4", ["e4","e5","d4","exd4","c3","Qf6","Bg5","Nc6","b3","Ke7","h4","Qxg5","f3","Nb4","a4","a6","Ra2","Nh6"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 4.", ["All My White Gambits"]),
  lineFromMoves(5, "white-gambits", "All My White Gambits — Line 5", ["e4","e5","d4","exd4","c3","Qg5","Qa4","Qe3+","Ne2","Ke7","Qd1","b5","a4","Qxc3+","Nd2","Qc5","Rg1","a6"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 5.", ["All My White Gambits"]),
  lineFromMoves(6, "white-gambits", "All My White Gambits — Line 6", ["e4","e5","d4","exd4","c3","Qh4","Qe2","Qf4","Qd3","Qh4","Be2","Nc6","Bd2","Na5","Be3","Qf6","Nd2","Qf4"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 6.", ["All My White Gambits"]),
  lineFromMoves(7, "white-gambits", "All My White Gambits — Line 7", ["e4","e5","d4","exd4","c3","Ke7","Qb3","c6","g3","h5","g4","dxc3","Qd5","g5","Bf4","c2","Qd1","d6"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 7.", ["All My White Gambits"]),
  lineFromMoves(8, "white-gambits", "All My White Gambits — Line 8", ["e4","e5","d4","exd4","c3","Be7","Qa4","Na6","f3","Bb4","Bd3","c6","Bh6","Ba3","Qxa6","Bb4","h3","Bd6"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 8.", ["All My White Gambits"]),
  lineFromMoves(9, "white-gambits", "All My White Gambits — Line 9", ["e4","e5","d4","exd4","c3","Bd6","Qd2","c6","a4","b6","Qxd4","Bb4","Qf6","Nh6","Bd3","d6","g4","Ba5"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 9.", ["All My White Gambits"]),
  lineFromMoves(10, "white-gambits", "All My White Gambits — Line 10", ["e4","e5","d4","exd4","c3","Bc5","Qd3","h6","Nd2","Qg5","Qb5","a6","h3","Kd8","Bc4","Nf6","g3","Be7"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 10.", ["All My White Gambits"]),
  lineFromMoves(11, "white-gambits", "All My White Gambits — Line 11", ["e4","e5","d4","exd4","c3","Bb4","Qh5","Bc5","Qd5","Na6","Qxd4","f6","e5","Nb8","Bb5","Be7","Be2","h5"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 11.", ["All My White Gambits"]),
  lineFromMoves(12, "white-gambits", "All My White Gambits — Line 12", ["e4","e5","d4","exd4","c3","Ba3","Qg4","f5","h3","g5","Nf3","a5","Bb5","Na6","Bf1","d5","Be2","fxg4"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 12.", ["All My White Gambits"]),
  lineFromMoves(13, "white-gambits", "All My White Gambits — Line 13", ["e4","e5","d4","exd4","c3","Nh6","Qf3","Nf5","Kd2","h5","Qxh5","Ne3","Qg5","a6","Qh4","g5","Bb5","Nc2"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 13.", ["All My White Gambits"]),
  lineFromMoves(14, "white-gambits", "All My White Gambits — Line 14", ["e4","e5","d4","exd4","c3","Nf6","Qg4","Na6","b4","h6","Qe2","Ng4","Qd1","Rh7","Bc4","h5","e5","f6"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 14.", ["All My White Gambits"]),
  lineFromMoves(15, "white-gambits", "All My White Gambits — Line 15", ["e4","e5","d4","exd4","c3","Ne7","Qh5","b6","Qd5","d6","Qg5","a5","Qxe7+","Bxe7","h4","Na6","Nd2","Bg5"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 15.", ["All My White Gambits"]),
  lineFromMoves(16, "white-gambits", "All My White Gambits — Line 16", ["e4","e5","Nc3","Nf6","f4","Nc6","Kf2","g6","Qe2","Nb4","Nb5","Rb8","Na3","Bg7","Nf3","c5","Kg3","Qb6"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 16.", ["All My White Gambits"]),
  lineFromMoves(17, "white-gambits", "All My White Gambits — Line 17", ["e4","e5","Nc3","Nf6","f4","Na6","Be2","Nc5","b4","Rb8","Bd3","d6","Ba6","Nfd7","Bxb7","Nd3+","Ke2","g5"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 17.", ["All My White Gambits"]),
  lineFromMoves(18, "white-gambits", "All My White Gambits — Line 18", ["e4","e5","Nc3","Nf6","f4","Qe7","Bd3","h5","Nd5","Rg8","Ne2","b5","g4","c6","Nb6","Nxe4","c3","exf4"], "Every gambit in one place — Danish, Vienna, King's Gambit, and more. Line 18.", ["All My White Gambits"]),
];
